import { officeReviewUrl } from './desk-review-link.js';
import { createHash } from 'node:crypto';
import { CHANNEL_INGRESS_USER_ID, parseBlobRef, type BlobRef, type DraftImageRef, type LifecycleAlbumRef, type LifecycleSourceRef } from '@hawa/contracts';
import { sourceCopyConfirmation } from '@hawa/domain';
import { type BlobStore } from '@hawa/db';
import { blobStoreFor } from './blob-store-context.js';
import { verifyReviewedSource, SourceConflict } from './lifecycle-source-store.js';
import { parseCompleteRevisionRequest, parseRejectionCategory, type OfficeApprovalProof, type RejectionCategory, type StructuredRevisionRequest } from '@hawa/domain';
import { IdempotencyConflictError, OUTBOX_SEND_MARK_SOURCE, RevisionRepository, type Database, type Kysely, sql, withRlsContext } from '@hawa/db';
import { LIFECYCLE_MESSAGES, escapeTelegramHtml, requesterLang, say } from '@hawa/integrations';
import { persistChatIntake, type ChatIntake } from './chat-intake.js';
import { decisionDraftFor, linkedLifecycleReplies, readNewBriefDecision, readRevisionPhotoDecision } from './lifecycle-chat-target.js';
import { lifecyclePhotoInput } from './lifecycle-photo.js';
import { verifyAlbumSnapshot } from './lifecycle-album.js';
import { DRAFT_READY_STATUSES, bridgeCanvaDraftRevision, closeAnsweredQuestion, outcomeHasDraft, transitionTaskForOutcome } from './canva-task-outcome.js';
import { evaluateCanvaExportQc } from '../core-helpers.js';
import { composeCanvaStatusMessage, officeDayExhaustedNote } from './canva-status-message.js';
import { canvaEditUrl, composeOfficeDraftAlert, findDraftImage } from './office-draft-alert.js';
import { designName } from './requester-turn.js';
import { namedOfficeReviewMode } from './google-oidc.js';
import { lockNamedReviewAuthority } from './named-review-authority.js';
import { initialManualOrigin } from './lifecycle-native-scope.js';

/** First projection of a request; later transitions must advance the same revision ledger. */
export interface OpenLifecycleProjection {
  requestId: string;
  tenantId: string;
  expectedRev: 0;
  rev: 1;
  key: string;
  draft: ChatIntake;
}

export interface OpenLifecycleResult {
  requestId: string;
  rev: 1;
  taskId: string;
  stage: 'designing' | 'manual';
  autoGenerate: boolean;
  autoGenerateDeclined?: string;
  design?: {
    clientId: string; rawText: string; sourcePlatform: string;
    variant?: { width: number; height: number }; designStudio: boolean;
    studioOptions?: ChatIntake['studioOptions'];
  };
}

export class LifecycleProjectionConflict extends Error {
  constructor(readonly code: 'STALE_REVISION' | 'IDEMPOTENCY_CONFLICT' | 'TASK_ALREADY_OWNED' | 'WRONG_STAGE' | 'UNVERIFIED_DESIGN' | 'NOT_CURRENT_DRAFT' | 'UNAUTHORIZED_ACTOR' | 'APPROVAL_EVIDENCE_CHANGED' | 'INVALID_CONFIRMATION' | 'WRONG_CHAT' | 'APPROVAL_CHANGED' | 'EVIDENCE_CHANGED' | 'INCOMPLETE_OBSERVATION' | 'EVIDENCE_MISMATCH' | 'PARENT_BRIEF_MISSING' | 'DAILY_CAP_REACHED' | 'RETRY_LIMIT_REACHED', message: string) {
    super(message);
  }
}

export interface OfficeDecisionProjection {
  requestId: string; tenantId: string; taskId: string; revisionId: string;
  actionId: string;
  /** `telegram_office` (ADR-040 addendum): an office member's words in their private Telegram chat. */
  actor: { userId: string; role: string; authMethod?: 'google_oidc' | 'telegram_office'; sessionHash?: string; telegramChatId?: string };
  reason: string;
  revisionRequest?: StructuredRevisionRequest;
  decision?: 'revision_requested' | 'approved' | 'rejected';
  rejectionCategory?: RejectionCategory;
  approvalProof?: OfficeApprovalProof;
  deskRequestFingerprint?: string;
  /** expectedRev ≥ 2: first decision is at 2→3; subsequent rounds are at (2+2k)→(3+2k). */
  expectedRev: number; rev: number; key: string;
}

export interface OfficeDecisionResult {
  requestId: string; taskId: string; revisionId: string; actionId: string;
  approvalId: string; taskState: string; rev: number; stage: 'manual' | 'approved' | 'rejected';
}

const OFFICE_REVISION_ROLES = new Set(['approver', 'art_director', 'creative_director', 'account_lead', 'office_admin', 'administrator']);
const OFFICE_APPROVAL_ROLES = new Set(['approver', 'art_director', 'creative_director', 'office_admin', 'administrator']);

/**
 * Request-owned office decision (revision-request or proof-bound approval). Works across all
 * revision rounds: first office decision is at expectedRev=2→rev=3; second is at (2+2k)→(3+2k).
 * The route validates that expectedRev and rev match the request's current revision before
 * calling here, so the projection only needs to confirm the advisory-lock read agrees.
 */
export async function projectLifecycleOfficeDecision(db: Kysely<Database>, input: OfficeDecisionProjection): Promise<OfficeDecisionResult> {
  const { requestId, tenantId, taskId, revisionId, actionId, actor, reason, key } = input;
  const { expectedRev, rev } = input;
  if (!Number.isInteger(expectedRev) || expectedRev < 2 || !Number.isInteger(rev) || rev !== expectedRev + 1) {
    throw new LifecycleProjectionConflict('STALE_REVISION', 'The office decision has an invalid revision pair');
  }
  const decision = input.decision || 'revision_requested';
  const revisionRequest = input.revisionRequest === undefined ? undefined : parseCompleteRevisionRequest(input.revisionRequest);
  if ((input.revisionRequest !== undefined && (!revisionRequest || revisionRequest.comment !== reason)) ||
      (decision === 'approved' && (!input.approvalProof || !/^[a-f0-9]{64}$/.test(input.deskRequestFingerprint || '') || revisionRequest)) ||
      (decision === 'revision_requested' && (input.approvalProof || input.rejectionCategory)) ||
      (decision === 'rejected' && (!parseRejectionCategory(input.rejectionCategory) || input.approvalProof || revisionRequest)) ||
      (decision === 'approved' && input.rejectionCategory)) {
    throw new LifecycleProjectionConflict('WRONG_STAGE', 'Structured revision feedback is invalid or differs from the reason');
  }
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', rev).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'This office revision has different content or action identity');
      }
      return receipt.result as unknown as OfficeDecisionResult;
    }
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== expectedRev) {
      throw new LifecycleProjectionConflict('STALE_REVISION', `The request is not at expected revision ${expectedRev}`);
    }
    if (request.owner !== 'restate' || request.stage !== 'in_review') {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'Only an in-review request may receive this decision');
    }
    if (request.current_task_id !== taskId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The office action names an older request task');
    }
    // ADR-126: a request opened without a run has no requester revision round. Its manual stage at a
    // later revision would route the requester's reply into automatic generation, so it is refused.
    if (decision === 'revision_requested' && await initialManualOrigin(trx, tenantId, requestId, taskId)) {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'A request opened for manual design can be approved or rejected, not returned for a requester revision');
    }
    const task = await trx.selectFrom('tasks').select(['request_id', 'current_design_revision_id', 'state', 'version', 'client_id', 'project_id'])
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirst();
    if (task?.request_id !== requestId || task.current_design_revision_id !== revisionId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The office action names a stale or unowned design revision');
    }
    if (task.state !== 'human_review') {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'The current draft is no longer awaiting office review');
    }
    const namedReviewerRequired = namedOfficeReviewMode() || actor.authMethod === 'google_oidc';
    let namedAuthority: Awaited<ReturnType<typeof lockNamedReviewAuthority>> = null;
    if (namedReviewerRequired) {
      if (actor.authMethod !== 'google_oidc' || actor.role !== 'approver' ||
          !actor.sessionHash || !task.client_id) {
        throw new LifecycleProjectionConflict('UNAUTHORIZED_ACTOR', 'A named, assigned reviewer is required');
      }
      namedAuthority = await lockNamedReviewAuthority(trx, {
        tenantId, userId: actor.userId, sessionHash: actor.sessionHash,
        clientId: task.client_id, projectId: task.project_id,
      });
      if (!namedAuthority) throw new LifecycleProjectionConflict('UNAUTHORIZED_ACTOR',
        'The reviewer session or client/project assignment was revoked before this decision');
    }
    if (!(decision === 'approved' || decision === 'rejected' ? OFFICE_APPROVAL_ROLES : OFFICE_REVISION_ROLES).has(actor.role)) {
      throw new LifecycleProjectionConflict('UNAUTHORIZED_ACTOR', 'An authorized office reviewer must request this revision');
    }
    let approval: Awaited<ReturnType<RevisionRepository['recordApproval']>>;
    try {
      approval = await new RevisionRepository(trx).recordApproval({
      tenantId, taskId, revisionId, decision, decidedBy: actor.userId,
      reason, nonce: `desk:${actionId}`, lifecycleRequestId: requestId,
      expectedTaskVersion: Number(task.version),
      decisionPayload: { lifecycleRequestId: requestId, approverRole: actor.role,
        ...(namedAuthority ? { authMethod: 'google_oidc', reviewerAssignmentId: namedAuthority.assignmentId,
          reviewerAssignmentVersion: namedAuthority.assignmentVersion,
          reviewClientId: task.client_id, reviewProjectId: task.project_id } : {}),
        // ADR-040 addendum: who decided in Telegram (the office member's private chat), for the audit.
        ...(actor.authMethod === 'telegram_office' ? { authMethod: 'telegram_office', telegramChatId: actor.telegramChatId } : {}),
        actionId, requestFingerprint: hash, ...(revisionRequest ? { revisionRequest } : {}),
        ...(input.rejectionCategory ? { rejectionCategory: input.rejectionCategory } : {}),
        ...(input.approvalProof ? { officeApprovalProof: input.approvalProof,
          deskRequestFingerprint: input.deskRequestFingerprint,
          qcRunId: input.approvalProof.qcRunId, qcReportHash: input.approvalProof.qcReportHash,
          pinnedExports: input.approvalProof.pinnedExports, captureEvidenceRequired: true,
          ...(input.approvalProof.rtlVisualReview ? { rtlVisualReview: {
            ...input.approvalProof.rtlVisualReview, reviewerId: actor.userId,
            qcRunId: input.approvalProof.qcRunId, confirmedAt: new Date().toISOString(),
          } } : {}) } : {}) },
      ...(input.approvalProof ? { expectedQcRunId: input.approvalProof.qcRunId,
        expectedQcReportHash: input.approvalProof.qcReportHash } : {}),
      }, trx);
    } catch (error) {
      if (decision === 'approved' && error instanceof Error &&
          /QA evidence changed|QA run|Canva approval|Canva QA|RTL visual review|Precondition failed/.test(error.message)) {
        throw new LifecycleProjectionConflict('APPROVAL_EVIDENCE_CHANGED', error.message);
      }
      throw error;
    }
    const stage = decision === 'approved' ? 'approved' : decision === 'rejected' ? 'rejected' : 'manual';
    const changed = await trx.updateTable('requests').set({ stage, rev, updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', expectedRev)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'The request changed during office revision');
    const taskState = (await trx.selectFrom('tasks').select('state')
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirstOrThrow()).state;
    const result: OfficeDecisionResult = { requestId, taskId, revisionId, actionId,
      approvalId: approval.id, taskState, rev, stage };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

function canonical(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`;
}

async function checkAlbum(trx: Kysely<Database>, tenantId: string, chatId: string,
  ref: LifecycleAlbumRef, sourceUpdate?: unknown): Promise<void> {
  const snapshot = await verifyAlbumSnapshot(trx, tenantId, ref, sourceUpdate);
  if (!snapshot || snapshot.chatId !== chatId)
    throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The album differs from its confirmed source');
  for (const image of ref.images) {
    const blob = (await sql<{ size: string; media_type: string }>`SELECT size, media_type
      FROM hawa.blobs WHERE sha256 = ${image.sha256}`.execute(trx)).rows[0];
    if (!blob || Number(blob.size) !== image.size || blob.media_type !== image.mediaType)
      throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'A confirmed album image is not stored');
  }
}

async function attachAlbum(trx: Kysely<Database>, tenantId: string, taskId: string, ref: LifecycleAlbumRef) {
  for (const image of ref.images) await sql`INSERT INTO hawa.task_files (tenant_id, task_id, sha256, role)
    VALUES (${tenantId}::uuid, ${taskId}::uuid, ${image.sha256}, 'reference_image') ON CONFLICT DO NOTHING`.execute(trx);
}

/** One transaction makes the task, its recorded outbox row, ownership and replay receipt inseparable. */
export async function projectLifecycleOpen(db: Kysely<Database>, input: OpenLifecycleProjection,
  sourceStore: BlobStore | null = blobStoreFor(db)): Promise<OpenLifecycleResult> {
  const { requestId, tenantId, draft, key } = input;
  const hash = createHash('sha256').update(canonical({ ...input, draft: { ...draft, tenantId } })).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    // Same request and same key serialize even when Core runs in several processes. This also
    // protects against two first projections with different keys racing on one request.
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 1).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The first projection has different content or key');
      }
      return receipt.result as unknown as OpenLifecycleResult;
    }
    const otherKey = await trx.selectFrom('lifecycle_projections').select(['request_id'])
      .where('tenant_id', '=', tenantId).where('idempotency_key', '=', key).executeTakeFirst();
    if (otherKey) throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'Projection key belongs to another request');
    const prior = await trx.selectFrom('requests').select(['rev'])
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (prior) throw new LifecycleProjectionConflict('STALE_REVISION', `Request already has revision ${prior.rev}`);

    let admittedSource: unknown;
    const sourceDecision = (await sql<{ payload: { draft: ChatIntake } }>`SELECT payload FROM hawa.inbox_events
      WHERE tenant_id=${tenantId}::uuid AND source_account_id='lifecycle_chat_open'
        AND payload->>'requestId'=${requestId} AND payload->'draft'->'lifecycleSource' IS NOT NULL LIMIT 1`.execute(trx)).rows[0];
    if (sourceDecision && canonical(sourceDecision.payload.draft) !== canonical(draft))
      throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The worker changed or omitted the reviewed source');
    let reviewed: Awaited<ReturnType<typeof verifyReviewedSource>> | undefined;
    if (draft.lifecycleSource) {
      const decision = await readNewBriefDecision(trx, tenantId, draft.lifecycleSource.confirmationUpdateId);
      if (!decision || !draft.clientId || decision.requestId !== requestId || decision.chatId !== draft.sourceChannelId ||
          canonical(decision.draft) !== canonical(draft) || draft.lifecycleImage || draft.lifecycleAlbum)
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The source is not bound to this new brief');
      try { reviewed = await verifyReviewedSource(trx, sourceStore, { tenantId, requestId, clientId: draft.clientId,
        chatId: draft.sourceChannelId, ref: draft.lifecycleSource, copy: draft.rawText }); }
      catch (error) {
        if (error instanceof SourceConflict) throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', error.message);
        throw error;
      }
      if (reviewed.upload.target) throw new LifecycleProjectionConflict('WRONG_STAGE', 'A revision source cannot open a new request');
      admittedSource = decision.sourceUpdate;
    }
    if (draft.lifecycleAlbum) {
      const decision = await readNewBriefDecision(trx, tenantId, draft.lifecycleAlbum.updateId);
      const decided = decision && decisionDraftFor(decision, requestId);
      if (draft.lifecycleImage || !decision || !decided ||
          decision.chatId !== draft.sourceChannelId || canonical(decided) !== canonical(draft))
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The album is not bound to this new brief');
      await checkAlbum(trx, tenantId, draft.sourceChannelId, draft.lifecycleAlbum);
      admittedSource = decision.sourceUpdate;
    }

    if (draft.lifecycleImage) {
      const decision = await readNewBriefDecision(trx, tenantId, draft.lifecycleImage.updateId);
      const decided = decision && decisionDraftFor(decision, requestId);
      if (!decision || !decided ||
          decision.chatId !== draft.sourceChannelId || canonical(decided) !== canonical(draft)) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The image is not bound to this Telegram decision');
      }
      const blob = (await sql<{ size: string; media_type: string }>`SELECT size, media_type
        FROM hawa.blobs WHERE sha256 = ${draft.lifecycleImage.sha256}`.execute(trx)).rows[0];
      if (!blob || Number(blob.size) !== draft.lifecycleImage.size ||
          blob.media_type !== draft.lifecycleImage.mediaType) {
        throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The admitted image is not stored');
      }
      admittedSource = decision.sourceUpdate;
    }

    let persisted: Awaited<ReturnType<typeof persistChatIntake>>;
    try {
      persisted = await persistChatIntake(trx, { ...draft, tenantId,
        ...(reviewed ? { reviewedSource: reviewed.evidence,
          ...(reviewed.upload.variant ? { variant: reviewed.upload.variant } : {}),
          copyEn: /[\u0600-\u06ff]/.test(draft.rawText) ? '' : draft.rawText,
          copyCkb: /[\u0600-\u06ff]/.test(draft.rawText) ? draft.rawText : '' } : {}),
        ...(admittedSource !== undefined ? { rawJson: admittedSource } : {}) }, { outboxState: 'recorded' });
    } catch (error) {
      if (error instanceof IdempotencyConflictError) {
        throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The source event already belongs to a different executor');
      }
      throw error;
    }
    const taskId = String(persisted.task.id);
    const creation = await trx.selectFrom('outbox_commands').select(['state', 'payload'])
      .where('tenant_id', '=', tenantId).where('aggregate_id', '=', taskId)
      .where('command_type', '=', 'task.created').executeTakeFirst();
    if (creation?.state !== 'delivered' || creation.payload.lifecycleOwner !== 'restate' || persisted.task.request_id) {
      throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task is not exclusively owned by this lifecycle');
    }
    const autoGenerate = creation.payload.autoGenerate === true && Boolean(persisted.task.client_id);
    const stage = autoGenerate ? 'designing' : 'manual';
    await trx.insertInto('requests').values({
      request_id: requestId, tenant_id: tenantId, root_task_id: taskId, current_task_id: taskId,
      parent_request_id: null, owner: 'restate', stage, rev: 1, chat_id: draft.sourceChannelId,
      draft_sent_at: null, question_asked_at: null,
    }).execute();
    const claimed = await trx.updateTable('tasks').set({ request_id: requestId })
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).where('request_id', 'is', null)
      .returning('id').executeTakeFirst();
    if (!claimed) throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task acquired another request owner');
    if (draft.lifecycleAlbum) await attachAlbum(trx, tenantId, taskId, draft.lifecycleAlbum);
    if (reviewed) await sql`INSERT INTO hawa.task_files(tenant_id,task_id,sha256,role)
      VALUES (${tenantId}::uuid,${taskId}::uuid,${reviewed.evidence.sourceSha256},'source_document') ON CONFLICT DO NOTHING`.execute(trx);
    if (draft.lifecycleImage) {
      await sql`INSERT INTO hawa.task_files (tenant_id, task_id, sha256, role)
        VALUES (${tenantId}::uuid, ${taskId}::uuid, ${draft.lifecycleImage.sha256}, 'reference_image')`.execute(trx);
    }
    const result: OpenLifecycleResult = {
      requestId, rev: 1, taskId, stage, autoGenerate,
      ...(persisted.autoGenerateDeclined ? { autoGenerateDeclined: persisted.autoGenerateDeclined } : {}),
      ...(autoGenerate ? { design: {
        clientId: String(persisted.task.client_id),
        rawText: String(creation.payload.rawRequestText || ''),
        sourcePlatform: String(creation.payload.sourcePlatform || 'telegram'),
        ...(creation.payload.variant && typeof creation.payload.variant === 'object'
          ? { variant: creation.payload.variant as { width: number; height: number } } : {}),
        designStudio: creation.payload.designStudio === true,
        ...(creation.payload.studioOptions && typeof creation.payload.studioOptions === 'object'
          ? { studioOptions: creation.payload.studioOptions as ChatIntake['studioOptions'] } : {}),
      } } : {}),
    };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev: 1, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

export interface DesignOutcomeProjection {
  requestId: string; tenantId: string; taskId: string; runId: string;
  /** expectedRev ≥ 1: first run is 1→2; revision runs are (1+2k)→(2+2k). */
  expectedRev: number; rev: number; key: string;
  report: { status: string; designId?: string; code?: string; detail?: string; runId?: string; notifyRequester?: boolean };
}

export interface DesignOutcomeResult {
  requestId: string; taskId: string; rev: number; stage: 'in_review' | 'manual' | 'awaiting_answer';
  status: string; revisionId?: string; message?: { text: string; parseMode: 'HTML' };
  question?: { id: string; text: string; options: string[] };
  officeAlert?: { chatId: string; text: string };
  /**
   * ADR-155: the same alert to every office member, the requester too when they are one (the first is
   * `officeAlert`, which a worker from before this change still reads).
   */
  officeAlerts?: Array<{ chatId: string; text: string }>;
  /**
   * ADR-155 addendum: the draft's alert as a photo, one per entry of `officeAlerts` with the same words
   * (a caption, and the text sent instead when the picture cannot be read). Only for a draft with a
   * picture; a worker from before this field sends `officeAlerts`.
   */
  officePhotoAlerts?: Array<{ chatId: string; text: string; image: DraftImageRef }>;
}

/**
 * A terminal design outcome and its Desk revision share the request's revision transaction.
 * Works across all rounds: first design is at expectedRev=1→rev=2; revision rounds are at
 * (1+2k)→(2+2k). The route validates the rev pair before calling here.
 */
export async function projectLifecycleDesignOutcome(db: Kysely<Database>, input: DesignOutcomeProjection): Promise<DesignOutcomeResult> {
  const { requestId, tenantId, taskId, key, report } = input;
  const { expectedRev, rev } = input;
  if (!Number.isInteger(expectedRev) || expectedRev < 1 || !Number.isInteger(rev) || rev !== expectedRev + 1) {
    throw new LifecycleProjectionConflict('STALE_REVISION', 'The design outcome has an invalid revision pair');
  }
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', rev).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The design projection has different content or key');
      }
      return receipt.result as unknown as DesignOutcomeResult;
    }
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== expectedRev) {
      throw new LifecycleProjectionConflict('STALE_REVISION', `Request is not at expected revision ${expectedRev}`);
    }
    if (request.owner !== 'restate' || request.stage !== 'designing' || request.current_task_id !== taskId) {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'This request is not designing the named task');
    }
    const task = await trx.selectFrom('tasks').select(['id', 'request_id', 'client_id', 'title', 'current_design_revision_id'])
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirst();
    if (!task || task.request_id !== requestId) {
      throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task is not owned by this request');
    }
    const status = report.status;
    const hasDraft = outcomeHasDraft(status, report.designId);
    let question: DesignOutcomeResult['question'];
    if (!hasDraft && status === 'DESIGN_FAILED' && report.code === 'NEEDS_CLARIFICATION' &&
        report.runId && /^[0-9a-f-]{36}$/i.test(report.runId)) {
      const row = (await sql<{ question: string | null; options: unknown }>`SELECT
          r.stages->'directed'->'clarify'->>'question' AS question,
          r.stages->'directed'->'clarify'->'options' AS options
        FROM hawa.design_studio_runs r
        WHERE r.tenant_id = ${tenantId}::uuid AND r.task_id = ${taskId}::uuid
          AND r.id = ${report.runId}::uuid AND r.status = 'failed'
          AND r.stages->'directed'->>'refused' = 'NEEDS_CLARIFICATION'
        LIMIT 1`.execute(trx)).rows[0];
      const options = Array.isArray(row?.options) ? row.options.filter((value): value is string =>
        typeof value === 'string' && value.trim().length > 0 && value.length <= 100) : [];
      if (row?.question?.trim() && row.question.length <= 500 && options.length >= 2 && options.length <= 3) {
        question = { id: report.runId, text: row.question.trim(), options };
      }
    }
    if (hasDraft) {
      if (!report.designId) throw new LifecycleProjectionConflict('WRONG_STAGE', 'A draft outcome needs its verified Canva design ID');
      const binding = await trx.selectFrom('canva_bindings').select(['client_id', 'status'])
        .where('tenant_id', '=', tenantId).where('task_id', '=', taskId)
        .where('canva_design_id', '=', report.designId).executeTakeFirst();
      if (!binding || binding.status !== 'bound' || binding.client_id !== task.client_id) {
        throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The reported Canva design is not bound to this task and client');
      }
    }
    const reason = hasDraft
      ? `Canva draft ${report.designId || ''} awaits visual review.`
      : question ? 'The design is waiting for the requester to answer a clarification question.'
      : `Automatic design ended ${status}${report.code ? ` (${report.code})` : ''}; an operator must follow up.`;
    let revisionId: string | undefined;
    let creation: { payload: Record<string, unknown> } | undefined;
    if (hasDraft) {
      creation = await trx.selectFrom('outbox_commands').select('payload')
        .where('tenant_id', '=', tenantId).where('aggregate_id', '=', taskId)
        .where('command_type', '=', 'task.created').executeTakeFirst();
      const bridged = await bridgeCanvaDraftRevision(trx, {
        revisionRepo: new RevisionRepository(trx), evaluateQc: evaluateCanvaExportQc,
      }, {
        tenantId, taskId, actorId: CHANNEL_INGRESS_USER_ID, status, designId: report.designId,
        canvaUrl: report.designId ? `https://www.canva.com/design/${report.designId}/edit` : undefined,
        fallbackCopy: Array.isArray(creation?.payload.exactCopy) ? creation.payload.exactCopy : undefined,
        reason,
      });
      revisionId = bridged.created ? bridged.revisionId : task.current_design_revision_id || undefined;
    } else {
      await transitionTaskForOutcome(trx, { tenantId, taskId, toState: question ? 'paused' : 'failed_operator',
        actorId: CHANNEL_INGRESS_USER_ID, reason,
        data: { outcome: status, ...(report.code ? { code: report.code } : {}) },
      });
    }
    const stage = hasDraft ? 'in_review' : question ? 'awaiting_answer' : 'manual';
    const changed = await trx.updateTable('requests').set({ stage, rev,
      ...(question ? { question_asked_at: null } : {}), updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', expectedRev)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'Request changed during outcome projection');
    const reviewUrl = officeReviewUrl({ taskId, ...(revisionId ? { revisionId } : {}) });
    // ADR-155: every office member (TELEGRAM_ALLOWED_USERS). It was the first only, and nobody when that
    // member was the requester (the owner's own requests), while the requester was still told that
    // someone from the office had been alerted.
    const officeChats = [...new Set((process.env.TELEGRAM_ALLOWED_USERS || '').split(',').map((v) => v.trim()).filter(Boolean))];
    // ADR-145: the requester hears the design by the name they know (the request's first task: a
    // revision task is titled by its change) and in the language their brief was written in.
    const root = await trx.selectFrom('tasks').select(['title', 'description'])
      .where('tenant_id', '=', tenantId).where('id', '=', request.root_task_id).executeTakeFirst();
    const requestTitle = root?.title || task.title;
    const lang = requesterLang(root?.description || requestTitle);
    const composed = question || report.notifyRequester === false ? undefined : composeCanvaStatusMessage({
      taskId, title: requestTitle, status, code: report.code, lang,
      reviewUrl,
      canvaUrl: report.designId ? `https://www.canva.com/design/${report.designId}/edit` : undefined,
      // #15: with no office chat to alert, "someone from the office will follow up here". It says what
      // is sent: every office member below hears of it (ADR-155).
      officeAlerted: officeChats.length > 0,
    });
    // ADR-155 addendum: a draft's alert names the design, who it is for and its Canva link, with no
    // internal IDs, and goes as a photo of the draft (officePhotoAlerts). `officeAlerts` keeps the same
    // words as text for a worker from before, and is what is sent when the picture cannot be.
    let officeText: string;
    let draftImage: DraftImageRef | undefined;
    if (hasDraft) {
      const client = task.client_id ? await trx.selectFrom('clients').select('name')
        .where('tenant_id', '=', tenantId).where('id', '=', task.client_id).executeTakeFirst() : undefined;
      const requestedBy = typeof creation?.payload.senderName === 'string' ? creation.payload.senderName : undefined;
      officeText = composeOfficeDraftAlert({ title: requestTitle, clientName: client?.name, requestedBy,
        revised: taskId !== request.root_task_id, canvaUrl: canvaEditUrl(report.designId!), reviewUrl,
        ...(DRAFT_READY_STATUSES.has(status) ? {} : { check: `${status}${report.code ? ` (${report.code})` : ''}` }) });
      draftImage = await findDraftImage(trx, { tenantId, taskId, designId: report.designId! });
    } else {
      // No design was named (an outcome naming one is a draft, outcomeHasDraft), so there is no Canva
      // link to give: the draft alert above carries it for every outcome that has a design.
      officeText = `Automatic design needs an operator in Hawa Desk. Task ${taskId}: ${status}${report.code ? ` (${report.code})` : ''}.` +
        (report.code === 'OFFICE_DAY_EXHAUSTED' ? officeDayExhaustedNote() : '') +
        (reviewUrl ? `\nOpen review (office sign-in required): ${reviewUrl}` : '');
    }
    const officeAlerts = officeChats.map((chatId) => ({ chatId, text: officeText }));
    const officePhotoAlerts = draftImage ? officeChats.map((chatId) => ({ chatId, text: officeText, image: draftImage! })) : [];
    // #14 (ADR-145): the question in plain words, answered with a number or in the requester's own words.
    const questionText = question
      ? say(LIFECYCLE_MESSAGES.oneQuestion, lang, {
        title: designName(requestTitle, lang),
        question: `<b>${escapeTelegramHtml(question.text)}</b>`,
        options: question.options.map((option, index) => `${index + 1}. ${escapeTelegramHtml(option)}`).join('\n'),
      })
      : undefined;
    const messageText = questionText || composed?.text;
    const result: DesignOutcomeResult = { requestId, taskId, rev, stage, status,
      ...(revisionId ? { revisionId } : {}),
      ...(question ? { question } : {}),
      ...(messageText ? { message: { text: messageText, parseMode: 'HTML' as const } } : {}),
      ...(officeAlerts.length ? { officeAlert: officeAlerts[0], officeAlerts } : {}),
      ...(officePhotoAlerts.length ? { officePhotoAlerts } : {}),
    };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

export interface LifecycleQuestionSentInput {
  requestId: string; tenantId: string; expectedRev: number; taskId: string;
  questionId: string; messageKey: string; messageId: string;
}

/** Confirm a question from the sender's committed Telegram mark, without advancing request rev. */
export async function confirmLifecycleQuestionSent(db: Kysely<Database>, input: LifecycleQuestionSentInput): Promise<
  { skipped: true } | { requestId: string; rev: number; taskId: string; questionId: string;
    messageId: string; sentAtMs: number }
> {
  const { requestId, tenantId, expectedRev, taskId, questionId, messageKey, messageId } = input;
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const request = await trx.selectFrom('requests').select(['owner', 'stage', 'rev',
      'current_task_id', 'question_asked_at'])
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request) throw new LifecycleProjectionConflict('WRONG_STAGE', 'Question request does not exist');
    if (request.owner !== 'restate' || request.stage !== 'awaiting_answer' ||
        Number(request.rev) !== expectedRev || request.current_task_id !== taskId) return { skipped: true };
    const receipt = await trx.selectFrom('lifecycle_projections').select('result')
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId)
      .where('rev', '=', expectedRev).executeTakeFirst();
    const result = receipt?.result as Partial<DesignOutcomeResult> | undefined;
    if (result?.stage !== 'awaiting_answer' || result.taskId !== taskId ||
        result.question?.id !== questionId) {
      throw new LifecycleProjectionConflict('EVIDENCE_MISMATCH', 'The current projection does not contain this question');
    }
    const mark = (await sql<{ received_at: Date; message_id: string | null }>`SELECT received_at,
        payload->>'messageId' AS message_id FROM hawa.inbox_events
      WHERE tenant_id = ${tenantId}::uuid AND source_account_id = ${OUTBOX_SEND_MARK_SOURCE}
        AND source_event_id = ${`lc:${messageKey}:send`}
        AND event_kind = 'telegram_message_sent'
      ORDER BY received_at ASC, id ASC LIMIT 1`.execute(trx)).rows[0];
    if (!mark) throw new Error('The question notice has no confirmed Telegram send mark yet');
    if (mark.message_id !== messageId) {
      throw new LifecycleProjectionConflict('EVIDENCE_MISMATCH', 'The question message ID differs from its confirmed send mark');
    }
    const sentAtMs = new Date(mark.received_at).getTime();
    if (!Number.isFinite(sentAtMs) || sentAtMs <= 0) throw new Error('The confirmed send mark has an invalid timestamp');
    if (!request.question_asked_at) {
      await trx.updateTable('requests').set({ question_asked_at: new Date(sentAtMs), updated_at: new Date() })
        .where('tenant_id', '=', tenantId).where('request_id', '=', requestId)
        .where('rev', '=', expectedRev).where('question_asked_at', 'is', null).execute();
    }
    return { requestId, rev: expectedRev, taskId, questionId, messageId,
      sentAtMs: request.question_asked_at ? new Date(request.question_asked_at).getTime() : sentAtMs };
  });
}

// ---------------------------------------------------------------------------
// Revision-round projection: requester submits their directive; manual → designing
// ---------------------------------------------------------------------------

export interface RequesterRevisionProjection {
  requestId: string; tenantId: string;
  /** The task whose revision the office requested: validated as current_task_id. */
  priorTaskId: string;
  /**
   * New design-round task that was intake-persisted with sourceEventId `lc-<requestId>-r<round>` and
   * lifecycleOwner 'restate'. Sent by the worker after it calls Core /internal/telegram/intake.
   */
  newTaskId: string;
  /** Round index ≥ 1 (first revision = 1). */
  round: number;
  directive: string;
  /** expectedRev is the request's current rev (manual stage, post-office-revise). rev = expectedRev + 1. */
  expectedRev: number; rev: number; key: string;
}

export interface RequesterRevisionResult {
  requestId: string; priorTaskId: string; newTaskId: string; round: number;
  rev: number; stage: 'designing'; runId: string;
}

/**
 * Moves a manual-stage request back to `designing` when the requester sends their revision
 * directive. Creates the new round's task ownership, then advances the request row.
 * expectedRev ≥ 3 (always after at least one office revise); rev = expectedRev + 1.
 */
export async function projectLifecycleRequesterRevision(
  db: Kysely<Database>,
  input: RequesterRevisionProjection,
): Promise<RequesterRevisionResult> {
  const { requestId, tenantId, priorTaskId, newTaskId, round, directive, key } = input;
  const { expectedRev, rev } = input;
  if (!Number.isInteger(expectedRev) || expectedRev < 3 || !Number.isInteger(rev) || rev !== expectedRev + 1 ||
      !Number.isInteger(round) || round < 1 || typeof directive !== 'string' || !directive.trim()) {
    throw new LifecycleProjectionConflict('STALE_REVISION', 'The requester revision has an invalid revision pair or round');
  }
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  const runId = `dr-${newTaskId}`;
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', rev).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'This requester revision has different content or key');
      }
      return receipt.result as unknown as RequesterRevisionResult;
    }
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== expectedRev) {
      throw new LifecycleProjectionConflict('STALE_REVISION', `Request is not at expected revision ${expectedRev}`);
    }
    if (request.owner !== 'restate' || request.stage !== 'manual') {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'Only a manual-stage request may accept a requester revision directive');
    }
    if (request.current_task_id !== priorTaskId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The directive names an older request task');
    }
    // The new task must have been created by intake with the lifecycle source key and restate owner.
    const newTask = await trx.selectFrom('tasks').select(['id', 'request_id'])
      .where('tenant_id', '=', tenantId).where('id', '=', newTaskId).executeTakeFirst();
    if (!newTask) throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The new round task does not exist');
    const creation = await trx.selectFrom('outbox_commands').select(['state', 'payload'])
      .where('tenant_id', '=', tenantId).where('aggregate_id', '=', newTaskId)
      .where('command_type', '=', 'task.created').executeTakeFirst();
    if (creation?.state !== 'delivered' || creation.payload.lifecycleOwner !== 'restate' || newTask.request_id !== null) {
      throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The new round task is not exclusively available for this lifecycle');
    }
    // Claim the new task and advance the request to designing.
    const claimed = await trx.updateTable('tasks').set({ request_id: requestId })
      .where('tenant_id', '=', tenantId).where('id', '=', newTaskId).where('request_id', 'is', null)
      .returning('id').executeTakeFirst();
    if (!claimed) throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The new round task acquired another request owner');
    const changed = await trx.updateTable('requests')
      .set({ stage: 'designing', rev, current_task_id: newTaskId, updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', expectedRev)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'Request changed during requester revision');
    const result: RequesterRevisionResult = { requestId, priorTaskId, newTaskId, round, rev, stage: 'designing', runId };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

/** Input for the combined lifecycle intake + requester-revision projection (Q/A loop). */
export interface RequesterRevisionWithIntakeProjection {
  requestId: string;
  tenantId: string;
  /** The task the request is currently on (must match request.current_task_id). */
  priorTaskId: string;
  /** Revision round ≥ 1 (same increment the Restate worker uses). */
  round: number;
  /** Source event key from the Telegram update that carried the directive. */
  directive: string;
  /** Source event id for the new task (must be unique, e.g. "lc-<requestId>-r<round>-u<updateId>"). */
  sourceEventId: string;
  /** The Telegram chat the update came from; must match request.chat_id. */
  sourceChannelId: string;
  /** Raw text of the directive (the requester's message). */
  rawText: string;
  /** Present only for an answer to the current clarification question. */
  questionId?: string;
  /** Hash of the complete source update, including its Telegram reply target. */
  sourceUpdateHash: string;
  /** The verified ingress update saved with the child task for source audit and replay. */
  sourceUpdate: unknown;
  /** Core-stored image for this exact update and selected request, if present. */
  lifecycleImage?: BlobRef;
  lifecycleAlbum?: LifecycleAlbumRef;
  lifecycleSource?: LifecycleSourceRef;
  /** The client the prior task belongs to (carried forward to the new task). */
  clientId: string | null;
  /** Current request revision (manual stage). rev = expectedRev + 1. */
  expectedRev: number;
  rev: number;
  key: string;
}

export interface RequesterRevisionWithIntakeResult extends RequesterRevisionResult {
  /** The directive text as trimmed. */
  directive: string;
  sourceUpdateHash: string;
  questionId?: string;
}

/**
 * Lifecycle Q/A loop: persists the requester's revision task from an incoming Telegram update,
 * then advances the request from manual → designing in one transaction. Used by the lifecycle
 * intake mode so Core can fully handle the update without a separate Restate VO round-trip.
 */
export async function projectLifecycleRequesterRevisionWithIntake(
  db: Kysely<Database>,
  input: RequesterRevisionWithIntakeProjection,
  sourceStore: BlobStore | null = blobStoreFor(db),
): Promise<RequesterRevisionWithIntakeResult> {
  const { requestId, tenantId, priorTaskId, round, directive, sourceEventId, sourceChannelId, rawText, clientId, key } = input;
  const { expectedRev, rev } = input;
  if (!Number.isInteger(expectedRev) || expectedRev < (input.questionId ? 2 : 3) ||
      !Number.isInteger(rev) || rev !== expectedRev + 1 ||
      !Number.isInteger(round) || round < 1 || typeof directive !== 'string' || !directive.trim()) {
    throw new LifecycleProjectionConflict('STALE_REVISION', 'Invalid revision pair or round for lifecycle requester revision with intake');
  }
  if (!/^[a-f0-9]{64}$/.test(input.sourceUpdateHash)) {
    throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The Telegram source update hash is invalid');
  }
  if (createHash('sha256').update(JSON.stringify(input.sourceUpdate)).digest('hex') !== input.sourceUpdateHash) {
    throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The Telegram update differs from its source hash');
  }
  const source = input.sourceUpdate && typeof input.sourceUpdate === 'object'
    ? input.sourceUpdate as Record<string, unknown> : null;
  const sourceMessage = source?.message && typeof source.message === 'object'
    ? source.message as Record<string, unknown> : null;
  const sourceImage = sourceMessage?.photo ?? sourceMessage?.document;
  const photoInput = lifecyclePhotoInput(input.sourceUpdate);
  const sourceConfirmation = sourceCopyConfirmation(input.sourceUpdate);
  // ADR-145: the words may be confirmed naturally ("yes", or the corrected text), with no command in the
  // update; the stored confirmation (checked with the source below) then carries the exact copy.
  const naturalConfirmation = Boolean(input.lifecycleSource) && !sourceConfirmation;
  if ((Boolean(sourceConfirmation) !== Boolean(input.lifecycleSource) && !naturalConfirmation) ||
      (input.lifecycleSource && (input.lifecycleImage || input.lifecycleAlbum || rawText.trim() !== directive ||
        (sourceConfirmation && sourceConfirmation.copy !== rawText))))
    throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The source confirmation does not match this exact copy');
  if (input.lifecycleAlbum && (input.lifecycleImage || sourceImage ||
      sourceMessage?.text !== directive || input.lifecycleAlbum.updateId !== source?.update_id)) {
    throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The album source does not match this directive');
  }
  // ADR-145: words sent just after a photo with no words may carry that photo (kept for them). Such a
  // photo is admitted only by its stored decision and its claim, checked below; any other image must
  // come in the update itself.
  const heldImage = !sourceImage && Boolean(input.lifecycleImage) && !input.lifecycleSource && !input.lifecycleAlbum &&
    typeof sourceMessage?.text === 'string';
  if (Boolean(sourceImage) !== Boolean(input.lifecycleImage) && !heldImage) {
    throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'A requester photo requires its stored image decision');
  }
  if (input.lifecycleImage && (!parseBlobRef(input.lifecycleImage) ||
      (!heldImage && (!photoInput || photoInput.directive !== directive.trim())) ||
      !Number.isSafeInteger(source?.update_id) || Number(source?.update_id) <= 0)) {
    throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The requester image does not match an admitted Telegram photo');
  }
  if (input.questionId !== undefined && !/^[0-9a-f-]{36}$/i.test(input.questionId)) {
    throw new LifecycleProjectionConflict('WRONG_STAGE', 'The answer has no valid question identity');
  }
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    // Idempotent receipt: if Core already ran this projection, return the cached result.
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', rev).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'This requester revision has different content or key');
      }
      return receipt.result as unknown as RequesterRevisionWithIntakeResult;
    }
    // Validate the request is in the expected state.
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== expectedRev) {
      throw new LifecycleProjectionConflict('STALE_REVISION', `Request is not at expected revision ${expectedRev}`);
    }
    const answering = input.questionId !== undefined;
    if (request.owner !== 'restate' || request.stage !== (answering ? 'awaiting_answer' : 'manual')) {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'The request is not waiting for this kind of requester reply');
    }
    if (request.current_task_id !== priorTaskId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The directive names an older request task');
    }
    if (request.chat_id !== sourceChannelId) {
      throw new LifecycleProjectionConflict('WRONG_CHAT', 'The update chat does not match the request');
    }
    let reviewed: Awaited<ReturnType<typeof verifyReviewedSource>> | undefined;
    if (input.lifecycleSource) {
      if (!clientId) throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'Source client is missing');
      try { reviewed = await verifyReviewedSource(trx, sourceStore, { tenantId, requestId, clientId,
        chatId: sourceChannelId, ref: input.lifecycleSource, copy: rawText }); }
      catch (error) {
        if (error instanceof SourceConflict) throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', error.message);
        throw error;
      }
      if (reviewed.upload.target?.requestId !== requestId || reviewed.upload.target.taskId !== priorTaskId ||
          reviewed.upload.target.rev !== expectedRev || reviewed.confirmation.payloadHash !== input.sourceUpdateHash)
        throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'Source review is bound to a different request revision');
    }
    if (input.lifecycleAlbum) {
      await checkAlbum(trx, tenantId, sourceChannelId, input.lifecycleAlbum, input.sourceUpdate);
      const reply = sourceMessage?.reply_to_message as { message_id?: unknown } | undefined;
      if (reply) {
        const links = await linkedLifecycleReplies(trx, tenantId, sourceChannelId, String(reply.message_id));
        if (links.length !== 1 || links[0].requestId !== requestId || links[0].rev !== expectedRev)
          throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The album reply no longer names the current request');
      }
    }
    if (input.lifecycleImage) {
      if (photoInput?.captionless) {
        const replies = await linkedLifecycleReplies(trx, tenantId, sourceChannelId, photoInput.replyMessageId!);
        if (replies.length !== 1 || replies[0].requestId !== requestId || replies[0].rev !== expectedRev) {
          throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT',
            'A captionless image must reply to the current request notice');
        }
      }
      const decision = await readRevisionPhotoDecision(trx, tenantId, Number(source!.update_id));
      if (!decision || decision.requestId !== requestId || decision.chatId !== sourceChannelId ||
          decision.payloadHash !== input.sourceUpdateHash ||
          canonical(decision.image) !== canonical(input.lifecycleImage) || Boolean(decision.heldPhotoUpdateId) !== heldImage) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The image is not bound to this requester revision');
      }
      if (decision.heldPhotoUpdateId) {
        // The kept photo is this image, from this chat, and was claimed by these words for this request.
        const held = (await sql<{ ok: boolean }>`SELECT EXISTS (SELECT 1 FROM hawa.inbox_events h
            JOIN hawa.inbox_events u ON u.tenant_id = h.tenant_id AND u.source_account_id = 'lifecycle_photo_used'
              AND u.source_event_id = h.source_event_id
            WHERE h.tenant_id = ${tenantId}::uuid AND h.source_account_id = 'lifecycle_photo_held'
              AND h.source_event_id = ${String(decision.heldPhotoUpdateId)} AND h.payload->>'chatId' = ${sourceChannelId}
              AND h.payload->'image'->>'sha256' = ${input.lifecycleImage.sha256}
              AND u.payload->>'byUpdateId' = ${String(source!.update_id)} AND u.payload->>'requestId' = ${requestId}) AS ok`.execute(trx)).rows[0];
        if (!held?.ok) throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The kept photo is not claimed by this requester revision');
      }
      const blob = (await sql<{ size: string; media_type: string }>`SELECT size, media_type
        FROM hawa.blobs WHERE sha256 = ${input.lifecycleImage.sha256}`.execute(trx)).rows[0];
      if (!blob || Number(blob.size) !== input.lifecycleImage.size ||
          blob.media_type !== input.lifecycleImage.mediaType) {
        throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The requester image is not stored');
      }
    }
    // A revision edits the prior design. Keep its factual copy, format and studio policy;
    // the new Telegram text supplies only the change directive.
    const parent = await trx.selectFrom('outbox_commands').select('payload')
      .where('tenant_id', '=', tenantId).where('aggregate_id', '=', priorTaskId)
      .where('command_type', '=', 'task.created').executeTakeFirst();
    const parentPayload = parent?.payload as Record<string, unknown> | undefined;
    if (!parentPayload || !Array.isArray(parentPayload.exactCopy) ||
        typeof parentPayload.designInstructions !== 'string') {
      throw new LifecycleProjectionConflict('PARENT_BRIEF_MISSING',
        'The current task has no complete source brief to revise');
    }
    const parentOptions = parentPayload.studioOptions && typeof parentPayload.studioOptions === 'object'
      ? parentPayload.studioOptions as Record<string, unknown> : {};
    let question: DesignOutcomeResult['question'];
    if (answering) {
      const last = await trx.selectFrom('lifecycle_projections').select('result')
        .where('tenant_id', '=', tenantId).where('request_id', '=', requestId)
        .where('rev', '=', expectedRev).executeTakeFirst();
      question = (last?.result as unknown as DesignOutcomeResult | undefined)?.question;
      if (!question || question.id !== input.questionId ||
          typeof parentOptions.parentTaskId !== 'string' ||
          typeof parentOptions.revisionDirective !== 'string' || !parentOptions.revisionDirective.trim()) {
        throw new LifecycleProjectionConflict('WRONG_STAGE', 'The current question or its parent design is missing');
      }
    }
    const inheritedOptions = Object.fromEntries(['tier', 'imagery', 'previews', 'holdForSelection']
      .filter((name) => parentOptions[name] !== undefined).map((name) => [name, parentOptions[name]]));
    const answerText = answering ? directive.trim().replace(/\s+/g, ' ').slice(0, 500) : '';
    const revisionDirective = question
      ? `${parentOptions.revisionDirective}\nAsked "${question.text}", the requester answered: ${answerText}`
      : directive.trim();
    // Persist the new task via chat-intake with lifecycleOwner: 'restate'.
    const draft: ChatIntake = {
      platform: 'telegram', sourceEventId, sourceChannelId,
      rawText, rawJson: input.sourceUpdate, title: directive.trim().slice(0, 200),
      ...(input.lifecycleAlbum ? { lifecycleAlbum: input.lifecycleAlbum } : {}),
      designInstructions: `${parentPayload.designInstructions}\n${question
        ? `Answer to "${question.text}": ${answerText}` : `Revision: ${directive.trim()}`}`,
      exactCopy: parentPayload.exactCopy,
      clientId, autoGenerate: true,
      ...(typeof parentPayload.headlineEn === 'string' ? { headlineEn: parentPayload.headlineEn } : {}),
      ...(typeof parentPayload.headlineCkb === 'string' ? { headlineCkb: parentPayload.headlineCkb } : {}),
      ...(typeof parentPayload.copyEn === 'string' ? { copyEn: parentPayload.copyEn } : {}),
      ...(typeof parentPayload.copyCkb === 'string' ? { copyCkb: parentPayload.copyCkb } : {}),
      ...(parentPayload.variant && typeof parentPayload.variant === 'object'
        ? { variant: parentPayload.variant as { width: number; height: number } } : {}),
      ...(typeof parentPayload.designStudio === 'boolean' ? { designStudio: parentPayload.designStudio } : {}),
      studioOptions: { ...inheritedOptions,
        parentTaskId: question ? parentOptions.parentTaskId as string : priorTaskId,
        revisionRound: round, revisionDirective,
        ...(question ? { clarified: true, answers: priorTaskId } : {}) } as ChatIntake['studioOptions'],
    };
    let persisted: Awaited<ReturnType<typeof persistChatIntake>>;
    try {
      persisted = await persistChatIntake(trx, { ...draft, tenantId,
        ...(reviewed ? { reviewedSource: reviewed.evidence,
          rawJson: { original: reviewed.upload.sourceUpdate, confirmation: reviewed.confirmation.sourceUpdate },
          ...(reviewed.upload.variant ? { variant: reviewed.upload.variant } : {}),
          exactCopy: [{ id: 'reviewed_source_copy', text: rawText, role: 'body', approved: true,
            language: /[\u0600-\u06ff]/.test(rawText) ? 'ckb' : 'en', direction: /[\u0600-\u06ff]/.test(rawText) ? 'rtl' : 'ltr' }],
          headlineEn: '', headlineCkb: '',
          copyEn: /[\u0600-\u06ff]/.test(rawText) ? '' : rawText, copyCkb: /[\u0600-\u06ff]/.test(rawText) ? rawText : '',
          designInstructions: `${String(parentPayload.designInstructions)}\n${reviewed.upload.instructions}`,
          studioOptions: { ...draft.studioOptions,
            revisionDirective: 'Replace the design copy with exactly the confirmed source copy. Preserve the other design requirements.' } } : {}),
      }, { outboxState: 'recorded' });
    } catch (error) {
      if (error instanceof IdempotencyConflictError) {
        throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The source event already belongs to a different executor');
      }
      throw error;
    }
    if (persisted.autoGenerateDeclined) {
      throw new LifecycleProjectionConflict('DAILY_CAP_REACHED',
        'This revision would exceed the automatic design limit');
    }
    const newTaskId = String(persisted.task.id);
    const runId = `dr-${newTaskId}`;
    // Claim the new task and advance the request.
    const claimed = await trx.updateTable('tasks').set({ request_id: requestId })
      .where('tenant_id', '=', tenantId).where('id', '=', newTaskId).where('request_id', 'is', null)
      .returning('id').executeTakeFirst();
    if (!claimed) throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The new task acquired another request owner');
    if (input.lifecycleAlbum) await attachAlbum(trx, tenantId, newTaskId, input.lifecycleAlbum);
    if (reviewed) await sql`INSERT INTO hawa.task_files(tenant_id,task_id,sha256,role)
      VALUES (${tenantId}::uuid,${newTaskId}::uuid,${reviewed.evidence.sourceSha256},'source_document') ON CONFLICT DO NOTHING`.execute(trx);
    if (input.lifecycleImage) {
      await sql`INSERT INTO hawa.task_files (tenant_id, task_id, sha256, role)
        VALUES (${tenantId}::uuid, ${newTaskId}::uuid, ${input.lifecycleImage.sha256}, 'reference_image')`.execute(trx);
    }
    if (question) {
      const closed = await closeAnsweredQuestion(trx, { tenantId, taskId: priorTaskId,
        revisionTaskId: newTaskId, actorId: CHANNEL_INGRESS_USER_ID });
      if (!closed.changed) throw new LifecycleProjectionConflict('WRONG_STAGE', 'The question task is no longer paused');
    }
    const changed = await trx.updateTable('requests')
      .set({ stage: 'designing', rev, current_task_id: newTaskId,
        ...(question ? { question_asked_at: null } : {}), updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', expectedRev)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'Request changed during requester revision with intake');
    const result: RequesterRevisionWithIntakeResult = {
      requestId, priorTaskId, newTaskId, round, rev, stage: 'designing', runId,
      directive: directive.trim(), sourceUpdateHash: input.sourceUpdateHash,
      ...(question ? { questionId: question.id } : {}),
    };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}
