import { createHash } from 'node:crypto';
import { CHANNEL_INGRESS_USER_ID } from '@hawa/contracts';
import { parseCompleteRevisionRequest, type OfficeApprovalProof, type StructuredRevisionRequest } from '@hawa/domain';
import { IdempotencyConflictError, RevisionRepository, type Database, type Kysely, sql, withRlsContext } from '@hawa/db';
import { persistChatIntake, type ChatIntake } from './chat-intake.js';
import { bridgeCanvaDraftRevision, outcomeHasDraft, transitionTaskForOutcome } from './canva-task-outcome.js';
import { evaluateCanvaExportQc } from '../core-helpers.js';
import { composeCanvaStatusMessage } from './canva-status-message.js';

/** First projection of a request; later transitions must advance the same revision ledger. */
export interface OpenLifecycleProjection {
  requestId: string;
  tenantId: string;
  expectedRev: 0;
  rev: 1;
  key: string;
  draft: ChatIntake;
}

export interface OpenLifecycleResult {
  requestId: string;
  rev: 1;
  taskId: string;
  stage: 'designing' | 'manual';
  autoGenerate: boolean;
  autoGenerateDeclined?: string;
  design?: {
    clientId: string; rawText: string; sourcePlatform: string;
    variant?: { width: number; height: number }; designStudio: boolean;
    studioOptions?: ChatIntake['studioOptions'];
  };
}

export class LifecycleProjectionConflict extends Error {
  constructor(readonly code: 'STALE_REVISION' | 'IDEMPOTENCY_CONFLICT' | 'TASK_ALREADY_OWNED' | 'WRONG_STAGE' | 'UNVERIFIED_DESIGN' | 'NOT_CURRENT_DRAFT' | 'UNAUTHORIZED_ACTOR' | 'APPROVAL_EVIDENCE_CHANGED', message: string) {
    super(message);
  }
}

export interface OfficeDecisionProjection {
  requestId: string; tenantId: string; taskId: string; revisionId: string;
  actionId: string; actor: { userId: string; role: string }; reason: string;
  revisionRequest?: StructuredRevisionRequest;
  decision?: 'revision_requested' | 'approved';
  approvalProof?: OfficeApprovalProof;
  deskRequestFingerprint?: string;
  expectedRev: 2; rev: 3; key: string;
}

export interface OfficeDecisionResult {
  requestId: string; taskId: string; revisionId: string; actionId: string;
  approvalId: string; taskState: string; rev: 3; stage: 'manual' | 'approved';
}

const OFFICE_REVISION_ROLES = new Set(['art_director', 'creative_director', 'account_lead', 'office_admin', 'administrator']);
const OFFICE_APPROVAL_ROLES = new Set(['art_director', 'creative_director', 'office_admin', 'administrator']);

/** First request-owned office decision. The request and approval/audit rows commit as one revision. */
export async function projectLifecycleOfficeDecision(db: Kysely<Database>, input: OfficeDecisionProjection): Promise<OfficeDecisionResult> {
  const { requestId, tenantId, taskId, revisionId, actionId, actor, reason, key } = input;
  const decision = input.decision || 'revision_requested';
  const revisionRequest = input.revisionRequest === undefined ? undefined : parseCompleteRevisionRequest(input.revisionRequest);
  if ((input.revisionRequest !== undefined && (!revisionRequest || revisionRequest.comment !== reason)) ||
      (decision === 'approved' && (!input.approvalProof || !/^[a-f0-9]{64}$/.test(input.deskRequestFingerprint || '') || revisionRequest)) ||
      (decision === 'revision_requested' && input.approvalProof)) {
    throw new LifecycleProjectionConflict('WRONG_STAGE', 'Structured revision feedback is invalid or differs from the reason');
  }
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 3).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'This office revision has different content or action identity');
      }
      return receipt.result as unknown as OfficeDecisionResult;
    }
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== 2) {
      throw new LifecycleProjectionConflict('STALE_REVISION', 'The request is not at expected revision 2');
    }
    if (request.owner !== 'restate' || request.stage !== 'in_review') {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'Only an in-review request may receive this decision');
    }
    if (request.current_task_id !== taskId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The office action names an older request task');
    }
    const task = await trx.selectFrom('tasks').select(['request_id', 'current_design_revision_id', 'state', 'version'])
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirst();
    if (task?.request_id !== requestId || task.current_design_revision_id !== revisionId) {
      throw new LifecycleProjectionConflict('NOT_CURRENT_DRAFT', 'The office action names a stale or unowned design revision');
    }
    if (task.state !== 'human_review') {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'The current draft is no longer awaiting office review');
    }
    if (!(decision === 'approved' ? OFFICE_APPROVAL_ROLES : OFFICE_REVISION_ROLES).has(actor.role)) {
      throw new LifecycleProjectionConflict('UNAUTHORIZED_ACTOR', 'An authorized office reviewer must request this revision');
    }
    let approval: Awaited<ReturnType<RevisionRepository['recordApproval']>>;
    try {
      approval = await new RevisionRepository(trx).recordApproval({
      tenantId, taskId, revisionId, decision, decidedBy: actor.userId,
      reason, nonce: `desk:${actionId}`, lifecycleRequestId: requestId,
      expectedTaskVersion: Number(task.version),
      decisionPayload: { lifecycleRequestId: requestId, approverRole: actor.role,
        actionId, requestFingerprint: hash, ...(revisionRequest ? { revisionRequest } : {}),
        ...(input.approvalProof ? { officeApprovalProof: input.approvalProof,
          deskRequestFingerprint: input.deskRequestFingerprint,
          qcRunId: input.approvalProof.qcRunId, qcReportHash: input.approvalProof.qcReportHash,
          pinnedExports: input.approvalProof.pinnedExports, captureEvidenceRequired: true,
          ...(input.approvalProof.rtlVisualReview ? { rtlVisualReview: {
            ...input.approvalProof.rtlVisualReview, reviewerId: actor.userId,
            qcRunId: input.approvalProof.qcRunId, confirmedAt: new Date().toISOString(),
          } } : {}) } : {}) },
      ...(input.approvalProof ? { expectedQcRunId: input.approvalProof.qcRunId,
        expectedQcReportHash: input.approvalProof.qcReportHash } : {}),
      }, trx);
    } catch (error) {
      if (decision === 'approved' && error instanceof Error &&
          /QA evidence changed|QA run|Canva approval|Canva QA|RTL visual review|Precondition failed/.test(error.message)) {
        throw new LifecycleProjectionConflict('APPROVAL_EVIDENCE_CHANGED', error.message);
      }
      throw error;
    }
    const stage = decision === 'approved' ? 'approved' : 'manual';
    const changed = await trx.updateTable('requests').set({ stage, rev: 3, updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 2)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'The request changed during office revision');
    const taskState = (await trx.selectFrom('tasks').select('state')
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirstOrThrow()).state;
    const result: OfficeDecisionResult = { requestId, taskId, revisionId, actionId,
      approvalId: approval.id, taskState, rev: 3, stage };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev: 3, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

function canonical(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`;
}

/** One transaction makes the task, its recorded outbox row, ownership and replay receipt inseparable. */
export async function projectLifecycleOpen(db: Kysely<Database>, input: OpenLifecycleProjection): Promise<OpenLifecycleResult> {
  const { requestId, tenantId, draft, key } = input;
  const hash = createHash('sha256').update(canonical({ ...input, draft: { ...draft, tenantId } })).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    // Same request and same key serialize even when Core runs in several processes. This also
    // protects against two first projections with different keys racing on one request.
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 1).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The first projection has different content or key');
      }
      return receipt.result as unknown as OpenLifecycleResult;
    }
    const otherKey = await trx.selectFrom('lifecycle_projections').select(['request_id'])
      .where('tenant_id', '=', tenantId).where('idempotency_key', '=', key).executeTakeFirst();
    if (otherKey) throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'Projection key belongs to another request');
    const prior = await trx.selectFrom('requests').select(['rev'])
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (prior) throw new LifecycleProjectionConflict('STALE_REVISION', `Request already has revision ${prior.rev}`);

    let persisted: Awaited<ReturnType<typeof persistChatIntake>>;
    try {
      persisted = await persistChatIntake(trx, { ...draft, tenantId }, { outboxState: 'recorded' });
    } catch (error) {
      if (error instanceof IdempotencyConflictError) {
        throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The source event already belongs to a different executor');
      }
      throw error;
    }
    const taskId = String(persisted.task.id);
    const creation = await trx.selectFrom('outbox_commands').select(['state', 'payload'])
      .where('tenant_id', '=', tenantId).where('aggregate_id', '=', taskId)
      .where('command_type', '=', 'task.created').executeTakeFirst();
    if (creation?.state !== 'delivered' || creation.payload.lifecycleOwner !== 'restate' || persisted.task.request_id) {
      throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task is not exclusively owned by this lifecycle');
    }
    const autoGenerate = creation.payload.autoGenerate === true && Boolean(persisted.task.client_id);
    const stage = autoGenerate ? 'designing' : 'manual';
    await trx.insertInto('requests').values({
      request_id: requestId, tenant_id: tenantId, root_task_id: taskId, current_task_id: taskId,
      parent_request_id: null, owner: 'restate', stage, rev: 1, chat_id: draft.sourceChannelId,
      draft_sent_at: null, question_asked_at: null,
    }).execute();
    const claimed = await trx.updateTable('tasks').set({ request_id: requestId })
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).where('request_id', 'is', null)
      .returning('id').executeTakeFirst();
    if (!claimed) throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task acquired another request owner');
    const result: OpenLifecycleResult = {
      requestId, rev: 1, taskId, stage, autoGenerate,
      ...(persisted.autoGenerateDeclined ? { autoGenerateDeclined: persisted.autoGenerateDeclined } : {}),
      ...(autoGenerate ? { design: {
        clientId: String(persisted.task.client_id),
        rawText: String(creation.payload.rawRequestText || ''),
        sourcePlatform: String(creation.payload.sourcePlatform || 'telegram'),
        ...(creation.payload.variant && typeof creation.payload.variant === 'object'
          ? { variant: creation.payload.variant as { width: number; height: number } } : {}),
        designStudio: creation.payload.designStudio === true,
        ...(creation.payload.studioOptions && typeof creation.payload.studioOptions === 'object'
          ? { studioOptions: creation.payload.studioOptions as ChatIntake['studioOptions'] } : {}),
      } } : {}),
    };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev: 1, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}

export interface DesignOutcomeProjection {
  requestId: string; tenantId: string; taskId: string; runId: string;
  expectedRev: 1; rev: 2; key: string;
  report: { status: string; designId?: string; code?: string; detail?: string; runId?: string; notifyRequester?: boolean };
}

export interface DesignOutcomeResult {
  requestId: string; taskId: string; rev: 2; stage: 'in_review' | 'manual';
  status: string; revisionId?: string; message?: { text: string; parseMode: 'HTML' };
  officeAlert?: { chatId: string; text: string };
}

/** A terminal design outcome and its Desk revision share the request's revision transaction. */
export async function projectLifecycleDesignOutcome(db: Kysely<Database>, input: DesignOutcomeProjection): Promise<DesignOutcomeResult> {
  const { requestId, tenantId, taskId, key, report } = input;
  const hash = createHash('sha256').update(canonical(input)).digest('hex');
  return withRlsContext(db, { tenantId, userId: CHANNEL_INGRESS_USER_ID, role: 'operator' }, async (trx) => {
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`lifecycle:${requestId}`}, 0))`.execute(trx);
    const receipt = await trx.selectFrom('lifecycle_projections').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 2).executeTakeFirst();
    if (receipt) {
      if (receipt.idempotency_key !== key || receipt.payload_sha256 !== hash) {
        throw new LifecycleProjectionConflict('IDEMPOTENCY_CONFLICT', 'The design projection has different content or key');
      }
      return receipt.result as unknown as DesignOutcomeResult;
    }
    const request = await trx.selectFrom('requests').selectAll()
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).executeTakeFirst();
    if (!request || Number(request.rev) !== 1) {
      throw new LifecycleProjectionConflict('STALE_REVISION', `Request is not at expected revision 1`);
    }
    if (request.owner !== 'restate' || request.stage !== 'designing' || request.current_task_id !== taskId) {
      throw new LifecycleProjectionConflict('WRONG_STAGE', 'This request is not designing the named task');
    }
    const task = await trx.selectFrom('tasks').select(['id', 'request_id', 'client_id', 'title', 'current_design_revision_id'])
      .where('tenant_id', '=', tenantId).where('id', '=', taskId).executeTakeFirst();
    if (!task || task.request_id !== requestId) {
      throw new LifecycleProjectionConflict('TASK_ALREADY_OWNED', 'The task is not owned by this request');
    }
    const status = report.status;
    const hasDraft = outcomeHasDraft(status, report.designId);
    if (hasDraft) {
      if (!report.designId) throw new LifecycleProjectionConflict('WRONG_STAGE', 'A draft outcome needs its verified Canva design ID');
      const binding = await trx.selectFrom('canva_bindings').select(['client_id', 'status'])
        .where('tenant_id', '=', tenantId).where('task_id', '=', taskId)
        .where('canva_design_id', '=', report.designId).executeTakeFirst();
      if (!binding || binding.status !== 'bound' || binding.client_id !== task.client_id) {
        throw new LifecycleProjectionConflict('UNVERIFIED_DESIGN', 'The reported Canva design is not bound to this task and client');
      }
    }
    const reason = hasDraft
      ? `Canva draft ${report.designId || ''} awaits visual review.`
      : `Automatic design ended ${status}${report.code ? ` (${report.code})` : ''}; an operator must follow up.`;
    let revisionId: string | undefined;
    if (hasDraft) {
      const creation = await trx.selectFrom('outbox_commands').select('payload')
        .where('tenant_id', '=', tenantId).where('aggregate_id', '=', taskId)
        .where('command_type', '=', 'task.created').executeTakeFirst();
      const bridged = await bridgeCanvaDraftRevision(trx, {
        revisionRepo: new RevisionRepository(trx), evaluateQc: evaluateCanvaExportQc,
      }, {
        tenantId, taskId, actorId: CHANNEL_INGRESS_USER_ID, status, designId: report.designId,
        canvaUrl: report.designId ? `https://www.canva.com/design/${report.designId}/edit` : undefined,
        fallbackCopy: Array.isArray(creation?.payload.exactCopy) ? creation.payload.exactCopy : undefined,
        reason,
      });
      revisionId = bridged.created ? bridged.revisionId : task.current_design_revision_id || undefined;
    } else {
      await transitionTaskForOutcome(trx, { tenantId, taskId, toState: 'failed_operator',
        actorId: CHANNEL_INGRESS_USER_ID, reason,
        data: { outcome: status, ...(report.code ? { code: report.code } : {}) },
      });
    }
    const stage = hasDraft ? 'in_review' : 'manual';
    const changed = await trx.updateTable('requests').set({ stage, rev: 2, updated_at: new Date() })
      .where('tenant_id', '=', tenantId).where('request_id', '=', requestId).where('rev', '=', 1)
      .returning('request_id').executeTakeFirst();
    if (!changed) throw new LifecycleProjectionConflict('STALE_REVISION', 'Request changed during outcome projection');
    const composed = report.notifyRequester === false ? undefined : composeCanvaStatusMessage({
      taskId, title: task.title, status, code: report.code,
      canvaUrl: report.designId ? `https://www.canva.com/design/${report.designId}/edit` : undefined,
    });
    const officeChat = (process.env.TELEGRAM_ALLOWED_USERS || '').split(',').map((v) => v.trim()).find(Boolean);
    const officeAlert = !hasDraft && officeChat && officeChat !== request.chat_id
      ? { chatId: officeChat, text: `Automatic design needs an operator in Hawa Desk. Task ${taskId}: ${status}${report.code ? ` (${report.code})` : ''}.` }
      : undefined;
    const messageText = composed?.text && !officeChat
      ? composed.text.replace('The office has been alerted and will follow up with you here.',
          'A person needs to review it in Hawa Desk and follow up with you here.')
      : composed?.text;
    const result: DesignOutcomeResult = { requestId, taskId, rev: 2, stage, status,
      ...(revisionId ? { revisionId } : {}),
      ...(messageText ? { message: { text: messageText, parseMode: 'HTML' as const } } : {}),
      ...(officeAlert ? { officeAlert } : {}),
    };
    await trx.insertInto('lifecycle_projections').values({
      tenant_id: tenantId, request_id: requestId, rev: 2, idempotency_key: key,
      payload_sha256: hash, result: result as unknown as Record<string, unknown>,
    }).execute();
    return result;
  });
}
