import fs from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

/**
 * The fonts the rasteriser is allowed to see, and the environment every rsvg-convert call runs in.
 *
 * Measurement (fontkit) opens the files in packages/creative/assets/fonts; drawing (rsvg-convert,
 * through pango) used to resolve family names from whatever the host had installed. On the Macs pango
 * draws through CoreText, which ignores FONTCONFIG_FILE and found a different Noto Sans Arabic in
 * ~/Library/Fonts (9.4% narrower than the pinned file), Helvetica for Cinzel, and a variable Inter.
 * In the image the committed fonts.conf also listed the system folders, a second copy of every face
 * under /usr/local/share/fonts, and the web subsets (*.woff2) that carry the same family names.
 *
 * So every rasterisation now gets a generated fonts.conf that lists only the repo's font folder and
 * the few system files the registry names (Verdana, which may not be redistributed), with the web
 * subsets rejected, and runs pango on its fontconfig backend so the Macs read that file too.
 */

/** Forces pango's fontconfig backend; on macOS the default (CoreText) never reads FONTCONFIG_FILE. */
export const PANGO_FONTCONFIG_BACKEND = 'fc';

/** Bumped whenever the generated file's shape changes, so an old generated folder is never reused. */
const GENERATED_CONFIG_VERSION = 1;

function registryPath(): string | undefined {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return [
    path.join(here, 'render-fonts.json'),
    path.resolve(here, '../../src/studio/render-fonts.json'),
    path.resolve(process.cwd(), 'packages/creative/src/studio/render-fonts.json'),
  ].find((candidate) => fs.existsSync(candidate));
}

/**
 * The system font files the registry lets the renderer use (`systemPaths`), those present on this
 * host. Only files that cannot be committed belong there: today the four Verdana faces.
 */
export function pinnedSystemFontFiles(): string[] {
  const file = registryPath();
  if (!file) return [];
  let families: Record<string, { systemPaths?: string[] }> = {};
  try {
    families = JSON.parse(fs.readFileSync(file, 'utf8')).families || {};
  } catch {
    return [];
  }
  const out: string[] = [];
  for (const family of Object.values(families)) {
    for (const p of family.systemPaths || []) {
      if (!out.includes(p) && fs.existsSync(p)) out.push(p);
    }
  }
  return out;
}

function xml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const generated = new Map<string, string>();

/**
 * A fonts.conf that lists only `fontsDir` and the registry's system files, generated once per host
 * under the temp folder and reused (its name is a hash of what it lists).
 *
 * Folders, not files, are what fontconfig scans, so the system files are linked into a folder of
 * their own. Built in a scratch folder and renamed into place, so two processes starting at once
 * both end up reading one complete file.
 */
export function pinnedFontconfigFile(fontsDir: string, systemFiles: string[] = pinnedSystemFontFiles()): string {
  const dir = path.resolve(fontsDir);
  const key = JSON.stringify({ v: GENERATED_CONFIG_VERSION, dir, systemFiles });
  const cached = generated.get(key);
  if (cached && fs.existsSync(cached)) return cached;

  const root = path.join(tmpdir(), 'hawa-fontconfig');
  const final = path.join(root, createHash('sha256').update(key).digest('hex').slice(0, 16));
  const conf = path.join(final, 'fonts.conf');
  if (!fs.existsSync(conf)) {
    fs.mkdirSync(root, { recursive: true });
    const scratch = fs.mkdtempSync(path.join(root, 'tmp-'));
    try {
      fs.mkdirSync(path.join(scratch, 'system'));
      for (const file of systemFiles) {
        fs.symlinkSync(file, path.join(scratch, 'system', path.basename(file)));
      }
      fs.writeFileSync(
        path.join(scratch, 'fonts.conf'),
        [
          '<?xml version="1.0"?>',
          '<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">',
          '<!-- Generated by packages/creative/src/studio/font-environment.ts. Do not edit. -->',
          '<fontconfig>',
          `  <dir>${xml(dir)}</dir>`,
          `  <dir>${xml(path.join(final, 'system'))}</dir>`,
          `  <cachedir>${xml(path.join(final, 'cache'))}</cachedir>`,
          '  <!-- Web subsets carry the same family names with fewer glyphs; fontkit never measures them. -->',
          '  <selectfont><rejectfont><glob>*.woff2</glob><glob>*.woff</glob></rejectfont></selectfont>',
          '</fontconfig>',
          '',
        ].join('\n'),
        { mode: 0o644 }
      );
      fs.renameSync(scratch, final);
    } catch (err) {
      fs.rmSync(scratch, { recursive: true, force: true });
      // Another process renamed its copy into place first; that one is as good as ours.
      if (!fs.existsSync(conf)) throw err;
    }
  }
  generated.set(key, conf);
  return conf;
}

/** The environment for an rsvg-convert (or fc-*) child: the pinned fonts, on fontconfig. */
export function rasteriserEnv(fontconfigFile: string): NodeJS.ProcessEnv {
  return { ...process.env, FONTCONFIG_FILE: fontconfigFile, PANGOCAIRO_BACKEND: PANGO_FONTCONFIG_BACKEND };
}

/** The repo's font folder, for callers outside the studio renderer. */
export function defaultFontsDir(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const candidates = [
    path.resolve(here, '../../assets/fonts'),
    path.resolve(process.cwd(), 'packages/creative/assets/fonts'),
  ];
  return candidates.find((candidate) => fs.existsSync(candidate)) ?? candidates[0];
}
