-- ADR-033: row-level-security membership checks run once per statement, not once per row.
-- Generated by packages/db/src/generate-rls-hoist-migration.ts from a database built as production is
-- (schema, rls, seed, migrations 001-015). Do not edit by hand: change the generator and regenerate.
-- 79 of 113 policies in schema hawa are rewritten; each rewrite is checked
-- against the definition it was generated from before it is replaced.

-- The clients the current user is an active member of in the current tenant; with for_write, only
-- memberships that may write (designer, client DNA manager), as can_write_client counts them.
CREATE OR REPLACE FUNCTION hawa.member_client_ids(for_write boolean) RETURNS uuid[]
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = hawa, public AS $$
  SELECT COALESCE(array_agg(cm.client_id), '{}'::uuid[])
  FROM hawa.client_memberships cm
  WHERE cm.tenant_id = hawa.current_tenant_id() AND cm.user_id = hawa.current_user_id() AND cm.active
    AND (NOT for_write OR cm.role = ANY (ARRAY['designer', 'client_dna_manager']::hawa.membership_role[]))
$$;

-- Each policy must still read as it did when this was generated (md5 of its fully qualified text).
DO $$
DECLARE
  expected text[][] := ARRAY[
    ARRAY['approvals', 'approvals_task_write', '580c66524e2c795f9372744c761285e7', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['artifacts', 'artifacts_task_write', 'b3064101f6c4d7b31c08c393600b9d9f', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['audit_events', 'audit_events_task_write', 'c591d8800da6970c1d3a127777e3deb5', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['backup_drills', 'backup_drills_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['backup_drills', 'backup_drills_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['brand_assets', 'brand_assets_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['brand_assets', 'brand_assets_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['channel_routes', 'channel_routes_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['channel_routes', 'channel_routes_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['client_dna_versions', 'client_dna_versions_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['client_dna_versions', 'client_dna_versions_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['client_memberships', 'client_memberships_admin', 'c9631606ad2d699568db2e1bb0728371', 'c9631606ad2d699568db2e1bb0728371'],
    ARRAY['client_memberships', 'client_memberships_select', 'a25bda23fceac31b91ec8301bfba9187', ''],
    ARRAY['client_rules', 'client_rules_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['client_rules', 'client_rules_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['clients', 'clients_client_select', 'b9cbceee086d91396672568b55082788', ''],
    ARRAY['clients', 'clients_client_write', '5d06c668023855a11309014f757ddcb6', '5d06c668023855a11309014f757ddcb6'],
    ARRAY['design_briefs', 'design_briefs_task_write', '5a8f79f6c22c4e638955bbfcc2c9ddc9', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['design_documents', 'design_documents_task_write', 'ccd4aade34641df32d7f6ed482e2c3b7', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['design_operations', 'design_operations_select', '0ff891a416caf6815b32f17302251983', ''],
    ARRAY['design_operations', 'design_operations_write', '', '5aaadfb59ca8b9e4739754e472d6160b'],
    ARRAY['design_plans', 'design_plans_task_write', '97e9724744514495560839fe1c1a7fbe', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['design_revisions', 'design_revisions_task_write', '0fbe47c23656b030b0ac46926a3ef3a1', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['drive_refs', 'drive_refs_select', '881063fd540be759cacc5657bfcb0cdd', ''],
    ARRAY['drive_refs', 'drive_refs_write', '2613e77d810403fe0d2122d7faad8f6d', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['eval_cases', 'eval_cases_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['eval_cases', 'eval_cases_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['eval_datasets', 'eval_datasets_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['eval_datasets', 'eval_datasets_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['eval_results', 'eval_results_select', 'bd01ad2190cb3861ac27662ddaf20e16', ''],
    ARRAY['eval_results', 'eval_results_write', '', '8b942ef50df0c3b92452d54f3fec9059'],
    ARRAY['eval_runs', 'eval_runs_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['eval_runs', 'eval_runs_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['feedback_events', 'feedback_events_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['feedback_events', 'feedback_events_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['glossary_terms', 'glossary_terms_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['glossary_terms', 'glossary_terms_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['inbox_events', 'inbox_events_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['inbox_events', 'inbox_events_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['integration_health', 'integration_health_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['integration_health', 'integration_health_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['integrations', 'integrations_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['integrations', 'integrations_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['knowledge_chunks', 'knowledge_chunks_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['knowledge_chunks', 'knowledge_chunks_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['knowledge_documents', 'knowledge_documents_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['knowledge_documents', 'knowledge_documents_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['message_attachments', 'message_attachments_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['message_attachments', 'message_attachments_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['message_events', 'message_events_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['message_events', 'message_events_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['model_deployments', 'model_deployments_select', '74cb439f45245a58b4ac1719987ab151', ''],
    ARRAY['model_deployments', 'model_deployments_write', 'ee8d17ab6ca5f0491d72c8132d5c43d7', 'ee8d17ab6ca5f0491d72c8132d5c43d7'],
    ARRAY['model_invocations', 'model_invocations_task_write', 'a63f2e5aa63f7050114433c49d05fcb3', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['outbox_commands', 'outbox_commands_tenant_select', '4ed97a3e97002de12480e184c1b6d33b', ''],
    ARRAY['outbox_commands', 'outbox_commands_tenant_write', '29079850b883d0d38416f6da3a5b93f0', '29079850b883d0d38416f6da3a5b93f0'],
    ARRAY['projects', 'projects_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['projects', 'projects_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['prompt_versions', 'prompt_versions_select', '74cb439f45245a58b4ac1719987ab151', ''],
    ARRAY['prompt_versions', 'prompt_versions_write', 'ee8d17ab6ca5f0491d72c8132d5c43d7', 'ee8d17ab6ca5f0491d72c8132d5c43d7'],
    ARRAY['publications', 'publications_task_write', '779408673bd212a85db6d644daeaa6d4', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['qc_profiles', 'qc_profiles_select', '74cb439f45245a58b4ac1719987ab151', ''],
    ARRAY['qc_profiles', 'qc_profiles_write', 'b4cfdaab36f652eaa6506006f311eba4', 'b4cfdaab36f652eaa6506006f311eba4'],
    ARRAY['qc_runs', 'qc_runs_task_write', 'b379b26cce710bdd84d3526cf3d64c74', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['review_requests', 'review_requests_task_write', '3f40a0d7b4f921730ca5c1a00e183562', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['rule_evidence', 'rule_evidence_select', '6b93439991204c57f65864de6d7e474b', ''],
    ARRAY['rule_evidence', 'rule_evidence_write', '70959eeae3e597796aa0bcd0d07a297e', '70959eeae3e597796aa0bcd0d07a297e'],
    ARRAY['sheet_syncs', 'sheet_syncs_task_write', '4bffa0fe7b5e59c2f549590456867731', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['task_events', 'task_events_task_write', 'd7eeef3978bd49132d6a3441eeb284cc', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['tasks', 'tasks_select', 'b8d52a929a2330e238c9f46caeaf0366', ''],
    ARRAY['tasks', 'tasks_write', '060a7be98b1fae6cb3241ae4269356ed', 'f50d5e59236506c3f8b773773c1f2abc'],
    ARRAY['templates', 'templates_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['templates', 'templates_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0'],
    ARRAY['tenant_memberships', 'tenant_memberships_admin', 'c9631606ad2d699568db2e1bb0728371', 'c9631606ad2d699568db2e1bb0728371'],
    ARRAY['tenant_memberships', 'tenant_memberships_select', 'a8893f19eedc55dd198f306f06fd4199', ''],
    ARRAY['tenants', 'tenants_admin', '7341e2484a1d92cb8dbd3be5f59f860d', 'ff05e6625b04930620762601457f5d0a'],
    ARRAY['tenants', 'tenants_select', '866847c051004db0c30953e6c754048f', ''],
    ARRAY['visual_examples', 'visual_examples_client_select', 'fb66377616e3aace0f92d6d02f6a31fe', ''],
    ARRAY['visual_examples', 'visual_examples_client_write', '7008eaffd5096a5699edf127b72ca2d0', '7008eaffd5096a5699edf127b72ca2d0']];
  row text[];
  found_qual text;
  found_check text;
  saved_path text := current_setting('search_path');
BEGIN
  PERFORM set_config('search_path', '', true);
  FOREACH row SLICE 1 IN ARRAY expected LOOP
    SELECT COALESCE(md5(pg_catalog.pg_get_expr(p.polqual, p.polrelid)), ''), COALESCE(md5(pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid)), '')
      INTO found_qual, found_check
      FROM pg_catalog.pg_policy p JOIN pg_catalog.pg_class c ON c.oid = p.polrelid JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'hawa' AND c.relname = row[1] AND p.polname = row[2];
    IF NOT FOUND OR found_qual <> row[3] OR found_check <> row[4] THEN
      RAISE EXCEPTION 'ADR-033: policy % on hawa.% is not the one this migration was generated from; nothing was changed', row[2], row[1];
    END IF;
  END LOOP;
  PERFORM set_config('search_path', saved_path, true);
END $$;

DROP POLICY approvals_task_write ON hawa.approvals;
CREATE POLICY approvals_task_write ON hawa.approvals AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = approvals.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY artifacts_task_write ON hawa.artifacts;
CREATE POLICY artifacts_task_write ON hawa.artifacts AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = artifacts.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY audit_events_task_write ON hawa.audit_events;
CREATE POLICY audit_events_task_write ON hawa.audit_events AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = audit_events.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY backup_drills_tenant_select ON hawa.backup_drills;
CREATE POLICY backup_drills_tenant_select ON hawa.backup_drills AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY backup_drills_tenant_write ON hawa.backup_drills;
CREATE POLICY backup_drills_tenant_write ON hawa.backup_drills AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY brand_assets_client_select ON hawa.brand_assets;
CREATE POLICY brand_assets_client_select ON hawa.brand_assets AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY brand_assets_client_write ON hawa.brand_assets;
CREATE POLICY brand_assets_client_write ON hawa.brand_assets AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY channel_routes_tenant_select ON hawa.channel_routes;
CREATE POLICY channel_routes_tenant_select ON hawa.channel_routes AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY channel_routes_tenant_write ON hawa.channel_routes;
CREATE POLICY channel_routes_tenant_write ON hawa.channel_routes AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY client_dna_versions_client_select ON hawa.client_dna_versions;
CREATE POLICY client_dna_versions_client_select ON hawa.client_dna_versions AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY client_dna_versions_client_write ON hawa.client_dna_versions;
CREATE POLICY client_dna_versions_client_write ON hawa.client_dna_versions AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY client_memberships_admin ON hawa.client_memberships;
CREATE POLICY client_memberships_admin ON hawa.client_memberships AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role]))));
DROP POLICY client_memberships_select ON hawa.client_memberships;
CREATE POLICY client_memberships_select ON hawa.client_memberships AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((user_id = hawa.current_user_id()) OR ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role, 'auditor'::hawa.membership_role]))))));
DROP POLICY client_rules_client_select ON hawa.client_rules;
CREATE POLICY client_rules_client_select ON hawa.client_rules AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY client_rules_client_write ON hawa.client_rules;
CREATE POLICY client_rules_client_write ON hawa.client_rules AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY clients_client_select ON hawa.clients;
CREATE POLICY clients_client_select ON hawa.clients AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY clients_client_write ON hawa.clients;
CREATE POLICY clients_client_write ON hawa.clients AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY design_briefs_task_write ON hawa.design_briefs;
CREATE POLICY design_briefs_task_write ON hawa.design_briefs AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = design_briefs.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY design_documents_task_write ON hawa.design_documents;
CREATE POLICY design_documents_task_write ON hawa.design_documents AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = design_documents.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY design_operations_select ON hawa.design_operations;
CREATE POLICY design_operations_select ON hawa.design_operations AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM (hawa.design_revisions d
     JOIN hawa.tasks t ON ((t.id = d.task_id)))
  WHERE ((d.id = design_operations.design_revision_id) AND ((t.client_id IS NULL) OR ((t.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (t.client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[]))))))))));
DROP POLICY design_operations_write ON hawa.design_operations;
CREATE POLICY design_operations_write ON hawa.design_operations AS PERMISSIVE FOR INSERT TO public WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM (hawa.design_revisions d
     JOIN hawa.tasks t ON ((t.id = d.task_id)))
  WHERE ((d.id = design_operations.design_revision_id) AND ((t.client_id IS NULL) OR ((t.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (t.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))))))));
DROP POLICY design_plans_task_write ON hawa.design_plans;
CREATE POLICY design_plans_task_write ON hawa.design_plans AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = design_plans.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY design_revisions_task_write ON hawa.design_revisions;
CREATE POLICY design_revisions_task_write ON hawa.design_revisions AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = design_revisions.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY drive_refs_select ON hawa.drive_refs;
CREATE POLICY drive_refs_select ON hawa.drive_refs AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM (hawa.publications p
     JOIN hawa.tasks t ON ((t.id = p.task_id)))
  WHERE ((p.id = drive_refs.publication_id) AND ((t.client_id IS NULL) OR ((t.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (t.client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[]))))))))));
DROP POLICY drive_refs_write ON hawa.drive_refs;
CREATE POLICY drive_refs_write ON hawa.drive_refs AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM (hawa.publications p
     JOIN hawa.tasks t ON ((t.id = p.task_id)))
  WHERE ((p.id = drive_refs.publication_id) AND ((t.client_id IS NULL) OR ((t.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (t.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY eval_cases_tenant_select ON hawa.eval_cases;
CREATE POLICY eval_cases_tenant_select ON hawa.eval_cases AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY eval_cases_tenant_write ON hawa.eval_cases;
CREATE POLICY eval_cases_tenant_write ON hawa.eval_cases AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY eval_datasets_tenant_select ON hawa.eval_datasets;
CREATE POLICY eval_datasets_tenant_select ON hawa.eval_datasets AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY eval_datasets_tenant_write ON hawa.eval_datasets;
CREATE POLICY eval_datasets_tenant_write ON hawa.eval_datasets AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY eval_results_select ON hawa.eval_results;
CREATE POLICY eval_results_select ON hawa.eval_results AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM hawa.eval_runs r
  WHERE ((r.id = eval_results.eval_run_id) AND ((r.tenant_id IS NULL) OR ((r.tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))))))));
DROP POLICY eval_results_write ON hawa.eval_results;
CREATE POLICY eval_results_write ON hawa.eval_results AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1
   FROM hawa.eval_runs r
  WHERE ((r.id = eval_results.eval_run_id) AND (r.tenant_id IS NOT NULL) AND ((r.tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'model_evaluator'::hawa.membership_role])))))));
DROP POLICY eval_runs_tenant_select ON hawa.eval_runs;
CREATE POLICY eval_runs_tenant_select ON hawa.eval_runs AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY eval_runs_tenant_write ON hawa.eval_runs;
CREATE POLICY eval_runs_tenant_write ON hawa.eval_runs AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY feedback_events_client_select ON hawa.feedback_events;
CREATE POLICY feedback_events_client_select ON hawa.feedback_events AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY feedback_events_client_write ON hawa.feedback_events;
CREATE POLICY feedback_events_client_write ON hawa.feedback_events AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY glossary_terms_client_select ON hawa.glossary_terms;
CREATE POLICY glossary_terms_client_select ON hawa.glossary_terms AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY glossary_terms_client_write ON hawa.glossary_terms;
CREATE POLICY glossary_terms_client_write ON hawa.glossary_terms AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY inbox_events_tenant_select ON hawa.inbox_events;
CREATE POLICY inbox_events_tenant_select ON hawa.inbox_events AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY inbox_events_tenant_write ON hawa.inbox_events;
CREATE POLICY inbox_events_tenant_write ON hawa.inbox_events AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY integration_health_tenant_select ON hawa.integration_health;
CREATE POLICY integration_health_tenant_select ON hawa.integration_health AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY integration_health_tenant_write ON hawa.integration_health;
CREATE POLICY integration_health_tenant_write ON hawa.integration_health AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY integrations_tenant_select ON hawa.integrations;
CREATE POLICY integrations_tenant_select ON hawa.integrations AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY integrations_tenant_write ON hawa.integrations;
CREATE POLICY integrations_tenant_write ON hawa.integrations AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY knowledge_chunks_client_select ON hawa.knowledge_chunks;
CREATE POLICY knowledge_chunks_client_select ON hawa.knowledge_chunks AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY knowledge_chunks_client_write ON hawa.knowledge_chunks;
CREATE POLICY knowledge_chunks_client_write ON hawa.knowledge_chunks AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY knowledge_documents_client_select ON hawa.knowledge_documents;
CREATE POLICY knowledge_documents_client_select ON hawa.knowledge_documents AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY knowledge_documents_client_write ON hawa.knowledge_documents;
CREATE POLICY knowledge_documents_client_write ON hawa.knowledge_documents AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY message_attachments_tenant_select ON hawa.message_attachments;
CREATE POLICY message_attachments_tenant_select ON hawa.message_attachments AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY message_attachments_tenant_write ON hawa.message_attachments;
CREATE POLICY message_attachments_tenant_write ON hawa.message_attachments AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY message_events_tenant_select ON hawa.message_events;
CREATE POLICY message_events_tenant_select ON hawa.message_events AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY message_events_tenant_write ON hawa.message_events;
CREATE POLICY message_events_tenant_write ON hawa.message_events AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY model_deployments_select ON hawa.model_deployments;
CREATE POLICY model_deployments_select ON hawa.model_deployments AS PERMISSIVE FOR SELECT TO public USING (((tenant_id IS NULL) OR ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id())))));
DROP POLICY model_deployments_write ON hawa.model_deployments;
CREATE POLICY model_deployments_write ON hawa.model_deployments AS PERMISSIVE FOR ALL TO public USING (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'model_evaluator'::hawa.membership_role]))))) WITH CHECK (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'model_evaluator'::hawa.membership_role])))));
DROP POLICY model_invocations_task_write ON hawa.model_invocations;
CREATE POLICY model_invocations_task_write ON hawa.model_invocations AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = model_invocations.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY outbox_commands_tenant_select ON hawa.outbox_commands;
CREATE POLICY outbox_commands_tenant_select ON hawa.outbox_commands AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id()))));
DROP POLICY outbox_commands_tenant_write ON hawa.outbox_commands;
CREATE POLICY outbox_commands_tenant_write ON hawa.outbox_commands AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))));
DROP POLICY projects_client_select ON hawa.projects;
CREATE POLICY projects_client_select ON hawa.projects AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY projects_client_write ON hawa.projects;
CREATE POLICY projects_client_write ON hawa.projects AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY prompt_versions_select ON hawa.prompt_versions;
CREATE POLICY prompt_versions_select ON hawa.prompt_versions AS PERMISSIVE FOR SELECT TO public USING (((tenant_id IS NULL) OR ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id())))));
DROP POLICY prompt_versions_write ON hawa.prompt_versions;
CREATE POLICY prompt_versions_write ON hawa.prompt_versions AS PERMISSIVE FOR ALL TO public USING (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'model_evaluator'::hawa.membership_role]))))) WITH CHECK (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'model_evaluator'::hawa.membership_role])))));
DROP POLICY publications_task_write ON hawa.publications;
CREATE POLICY publications_task_write ON hawa.publications AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = publications.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY qc_profiles_select ON hawa.qc_profiles;
CREATE POLICY qc_profiles_select ON hawa.qc_profiles AS PERMISSIVE FOR SELECT TO public USING (((tenant_id IS NULL) OR ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id())))));
DROP POLICY qc_profiles_write ON hawa.qc_profiles;
CREATE POLICY qc_profiles_write ON hawa.qc_profiles AS PERMISSIVE FOR ALL TO public USING (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role]))))) WITH CHECK (((tenant_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])))));
DROP POLICY qc_runs_task_write ON hawa.qc_runs;
CREATE POLICY qc_runs_task_write ON hawa.qc_runs AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = qc_runs.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY review_requests_task_write ON hawa.review_requests;
CREATE POLICY review_requests_task_write ON hawa.review_requests AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = review_requests.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY rule_evidence_select ON hawa.rule_evidence;
CREATE POLICY rule_evidence_select ON hawa.rule_evidence AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM hawa.client_rules r
  WHERE ((r.id = rule_evidence.rule_id) AND ((r.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (r.client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[]))))))));
DROP POLICY rule_evidence_write ON hawa.rule_evidence;
CREATE POLICY rule_evidence_write ON hawa.rule_evidence AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM hawa.client_rules r
  WHERE ((r.id = rule_evidence.rule_id) AND ((r.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (r.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM hawa.client_rules r
  WHERE ((r.id = rule_evidence.rule_id) AND ((r.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (r.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))))));
DROP POLICY sheet_syncs_task_write ON hawa.sheet_syncs;
CREATE POLICY sheet_syncs_task_write ON hawa.sheet_syncs AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = sheet_syncs.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY task_events_task_write ON hawa.task_events;
CREATE POLICY task_events_task_write ON hawa.task_events AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (EXISTS ( SELECT 1
   FROM hawa.tasks tx
  WHERE ((tx.id = task_events.task_id) AND ((tx.client_id IS NULL) OR ((tx.tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (tx.client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY tasks_select ON hawa.tasks;
CREATE POLICY tasks_select ON hawa.tasks AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND (((client_id IS NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id())))) OR ((client_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[]))))))));
DROP POLICY tasks_write ON hawa.tasks;
CREATE POLICY tasks_write ON hawa.tasks AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (((client_id IS NULL) AND ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role, 'requester'::hawa.membership_role])))) OR ((client_id IS NOT NULL) AND ((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))))))) WITH CHECK ((tenant_id = hawa.current_tenant_id()));
DROP POLICY templates_client_select ON hawa.templates;
CREATE POLICY templates_client_select ON hawa.templates AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY templates_client_write ON hawa.templates;
CREATE POLICY templates_client_write ON hawa.templates AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
DROP POLICY tenant_memberships_admin ON hawa.tenant_memberships;
CREATE POLICY tenant_memberships_admin ON hawa.tenant_memberships AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role])))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role]))));
DROP POLICY tenant_memberships_select ON hawa.tenant_memberships;
CREATE POLICY tenant_memberships_select ON hawa.tenant_memberships AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((user_id = hawa.current_user_id()) OR ((tenant_id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role]))))));
DROP POLICY tenants_admin ON hawa.tenants;
CREATE POLICY tenants_admin ON hawa.tenants AS PERMISSIVE FOR UPDATE TO public USING (((id = hawa.current_tenant_id()) AND (SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role])))) WITH CHECK ((id = hawa.current_tenant_id()));
DROP POLICY tenants_select ON hawa.tenants;
CREATE POLICY tenants_select ON hawa.tenants AS PERMISSIVE FOR SELECT TO public USING (((id = hawa.current_tenant_id()) AND ((id = hawa.current_tenant_id()) AND (SELECT hawa.is_tenant_member(hawa.current_tenant_id())))));
DROP POLICY visual_examples_client_select ON hawa.visual_examples;
CREATE POLICY visual_examples_client_select ON hawa.visual_examples AS PERMISSIVE FOR SELECT TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'auditor'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(false))::uuid[])))));
DROP POLICY visual_examples_client_write ON hawa.visual_examples;
CREATE POLICY visual_examples_client_write ON hawa.visual_examples AS PERMISSIVE FOR ALL TO public USING (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[]))))) WITH CHECK (((tenant_id = hawa.current_tenant_id()) AND ((SELECT hawa.has_tenant_role(hawa.current_tenant_id(), ARRAY['administrator'::hawa.membership_role, 'operator'::hawa.membership_role])) OR (client_id = ANY ((SELECT hawa.member_client_ids(true))::uuid[])))));
