import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import {
  OFFICE_PHOTO_LIMITS,
  officePhotoEntrySchema,
  officePhotoExclusions,
  officePhotoTagsSchema,
  parseOfficePhotoLibrary,
  selectOfficeLibraryPhotos,
  type OfficePhotoEntry,
  type OfficePhotoTags,
} from '../src/studio/office-photo-library.js';
import {
  computeOfficePhotoFeatures,
  ingestOfficePhotoFolder,
  loadOfficeLibraryPhoto,
  officePhotoClientDir,
  officePhotoLibraryRoot,
  parseOfficePhotoTagSheet,
  readOfficePhotoLibrary,
} from '../src/studio/office-photo-library-store.js';
import { syntheticPhoto, flatPng } from './fixtures/synthetic-photos.js';

/**
 * ADR-280: the office photo library. Every photo here is generated by the seeded synthetic-photo
 * fixture; no client media is committed.
 */

const sha = (s: string | Buffer) => createHash('sha256').update(s).digest('hex');
const tmpRoots: string[] = [];
const tmp = (prefix: string) => { const d = mkdtempSync(path.join(tmpdir(), prefix)); tmpRoots.push(d); return d; };
afterAll(() => { for (const d of tmpRoots) rmSync(d, { recursive: true, force: true }); });

const REVIEWED: Partial<OfficePhotoTags> = { usable: true, peoplePresent: true, consent: 'granted' };

/** A manifest entry with sensible defaults; `seed` makes the hashes distinct. */
function entry(seed: string, over: { tags?: Partial<OfficePhotoTags>; width?: number; height?: number; sharpness?: number; quiet?: 'top' | 'bottom' | 'left' | 'right' | 'none'; status?: 'usable' | 'excluded'; excludedReasons?: OfficePhotoEntry['excludedReasons'] } = {}): OfficePhotoEntry {
  const hash = sha(seed);
  const width = over.width ?? 1080, height = over.height ?? 1350;
  const tags = officePhotoTagsSchema.parse({ ...REVIEWED, ...over.tags });
  const features = { version: 1 as const, meanLuminance: 0.5, sharpness: over.sharpness ?? 0.8, soft: (over.sharpness ?? 0.8) < 0.45, quietArea: over.quiet ?? 'top',
    quietLuminance: 0.9, bands: { top: 0.2, bottom: 1.5, left: 1, right: 1 }, salient: { x: 0.5, y: 0.7 }, dominantColors: [{ hex: '#EEEEF2', share: 0.4 }] };
  const base = { id: `olp_${hash.slice(0, 16)}`, sha256: hash, storedSha256: hash, file: `photos/${hash}.png`, sourceName: `${seed}.png`, mimeType: 'image/png' as const,
    fileBytes: 1000, width, height, orientation: width / height > 1.05 ? 'landscape' as const : width / height < 0.95 ? 'portrait' as const : 'square' as const,
    features, tags, ingestedAt: '2026-10-03T00:00:00.000Z' };
  const reasons = over.excludedReasons ?? officePhotoExclusions(base);
  return officePhotoEntrySchema.parse({ ...base, excludedReasons: reasons, status: over.status ?? (reasons.length ? 'excluded' : 'usable') });
}

const library = (photos: OfficePhotoEntry[]) => parseOfficePhotoLibrary({ version: 1, clientId: 'kaae', updatedAt: '2026-10-03T00:00:00.000Z', photos });
const BRIEF = { width: 1080, height: 1350 };

describe('library manifest schema (ADR-280)', () => {
  it('parses a valid manifest and refuses unknown keys, bad hashes, a mismatched status, path tricks, disallowed types and oversize files', () => {
    const good = entry('a', { tags: { subjects: ['school'], events: ['field visit'] } });
    expect(library([good]).photos).toHaveLength(1);
    const bad = (patch: Record<string, unknown>) => () => parseOfficePhotoLibrary({ version: 1, clientId: 'kaae', updatedAt: '2026-10-03T00:00:00.000Z', photos: [{ ...good, ...patch }] });
    expect(bad({ extra: 1 })).toThrow(/OFFICE_PHOTO_LIBRARY_INVALID/);
    expect(bad({ sha256: 'xyz' })).toThrow(/sha256/);
    expect(bad({ status: 'excluded' })).toThrow(/excludedReasons/);
    expect(bad({ file: '../../etc/passwd' })).toThrow(/file/);
    expect(bad({ mimeType: 'image/gif' })).toThrow(/mimeType/);
    expect(bad({ fileBytes: OFFICE_PHOTO_LIMITS.maxFileBytes + 1 })).toThrow(/fileBytes/);
    expect(bad({ id: 'olp_0000000000000000' })).toThrow(/first 16 hex/);
    expect(bad({ orientation: 'landscape' })).toThrow(/orientation/);
    expect(bad({ tags: { ...good.tags, consent: 'maybe' } })).toThrow(/consent/);
    expect(bad({ tags: { ...good.tags, keywords: ['<script>'] } })).toThrow(/keywords/);
    expect(() => parseOfficePhotoLibrary({ version: 2, clientId: 'kaae', updatedAt: '2026-10-03T00:00:00.000Z', photos: [] })).toThrow(/version/);
    expect(() => parseOfficePhotoLibrary({ version: 1, clientId: '../x', updatedAt: '2026-10-03T00:00:00.000Z', photos: [] })).toThrow(/clientId/);
    expect(() => library([good, good])).toThrow(/duplicate/);
  });

  it('a photo is usable only once a person reviewed it, stated people and recorded consent; never generated, small or blurred', () => {
    const reasons = (tags: Partial<OfficePhotoTags>, extra: { width?: number; sharpness?: number } = {}) =>
      officePhotoExclusions({ tags: officePhotoTagsSchema.parse(tags), width: extra.width ?? 1080, height: 1350, mimeType: 'image/png', features: { sharpness: extra.sharpness ?? 0.8 } });
    expect(reasons(REVIEWED)).toEqual([]);
    expect(reasons({ usable: true, peoplePresent: false })).toEqual([]);
    expect(reasons({})).toEqual(['not_reviewed', 'people_unknown']);
    expect(reasons({ ...REVIEWED, usable: false })).toEqual(['excluded_by_office']);
    expect(reasons({ ...REVIEWED, consent: 'not_granted' })).toEqual(['no_consent']);
    expect(reasons({ ...REVIEWED, consent: 'unknown' })).toEqual(['consent_not_recorded']);
    expect(reasons({ ...REVIEWED, consent: 'not_required' })).toEqual([]);
    expect(reasons({ ...REVIEWED, generated: true })).toEqual(['generated']);
    expect(reasons(REVIEWED, { width: 600 })).toEqual(['too_small']);
    expect(reasons(REVIEWED, { sharpness: 0.2 })).toEqual(['too_soft']);
  });
});

describe('retrieval (ADR-280)', () => {
  const visit = entry('visit', { tags: { description: 'Evaluators visiting a primary school classroom', subjects: ['school', 'classroom', 'k12'], events: ['field visit'], keywords: ['evaluators', 'students'], shot: 'classroom_or_interior' } });
  const forum = entry('forum', { width: 1600, height: 1067, tags: { description: 'Speaker at the education forum', subjects: ['forum', 'speaker'], events: ['conference'], keywords: ['education'] } });
  const building = entry('building', { tags: { usable: true, peoplePresent: false, subjects: ['building', 'campus'], keywords: ['university', 'accreditation'] } });
  const visitSoft = entry('visit-soft', { sharpness: 0.35, tags: { subjects: ['school'], events: ['field visit'], keywords: ['students'] } });

  it('ranks the photo of the same kind of event first, with reasons, and returns 1-3', () => {
    const out = selectOfficeLibraryPhotos(library([forum, building, visit, visitSoft]), { ...BRIEF, copy: ['KAAE K-12 Pilot Study', 'Field Visit Report', 'Insights from KAAE school field visits'] });
    expect(out.picks[0].id).toBe(visit.id);
    expect(out.picks[0].reasons.join(' ')).toMatch(/same kind of event: field visit/);
    expect(out.picks[0].reasons.join(' ')).toMatch(/matches the brief's words: .*school/);
    expect(out.picks.length).toBeGreaterThanOrEqual(1);
    expect(out.picks.length).toBeLessThanOrEqual(3);
    // The soft photo of the same event ranks below the sharp one; the forum has nothing in common.
    expect(out.picks.map((p) => p.id)).not.toContain(forum.id);
    const soft = out.picks.find((p) => p.id === visitSoft.id);
    if (soft) expect(soft.score.total).toBeLessThan(out.picks[0].score.total);
    expect(out.briefEvents).toContain('field_visit');
  });

  it('is deterministic: the same picks whatever order the manifest lists the photos in', () => {
    const brief = { ...BRIEF, copy: ['Education Forum 2026', 'Keynote speaker'], eventWords: ['conference'] };
    const a = selectOfficeLibraryPhotos(library([forum, building, visit]), brief);
    const b = selectOfficeLibraryPhotos(library([visit, forum, building]), brief);
    expect(b).toEqual(a);
    expect(a.picks[0].id).toBe(forum.id);
    expect(a.peopleFocused).toBe(true);
  });

  it('prefers people for a brief about people, and the format-fitting orientation when all else is equal', () => {
    const people = entry('people', { tags: { subjects: ['accreditation'], peoplePresent: true, consent: 'granted', usable: true } });
    const empty = entry('empty', { tags: { subjects: ['accreditation'], peoplePresent: false, usable: true } });
    const out = selectOfficeLibraryPhotos(library([empty, people]), { ...BRIEF, copy: ['Meet our accreditation evaluators'] });
    expect(out.picks[0].id).toBe(people.id);
    const portrait = entry('portrait', { tags: { usable: true, peoplePresent: false, subjects: ['campus'] } });
    const landscape = entry('landscape', { width: 2000, height: 1000, tags: { usable: true, peoplePresent: false, subjects: ['campus'] } });
    const fit = selectOfficeLibraryPhotos(library([landscape, portrait]), { ...BRIEF, copy: ['Campus open day'] });
    expect(fit.picks[0].id).toBe(portrait.id);
    expect(fit.picks[0].score.orientation).toBe(1);
  });

  it('never returns an excluded, unreviewed, consent-less, generated, small or blurred photo, however well it matches', () => {
    const tags = { subjects: ['school'], events: ['field visit'] };
    const photos = [
      entry('x1', { tags: { ...tags, usable: false } }),
      entry('x2', { tags: { ...tags, usable: undefined } }),
      entry('x3', { tags: { ...tags, consent: 'not_granted' } }),
      entry('x4', { tags: { ...tags, consent: 'unknown' } }),
      entry('x5', { tags: { ...tags, generated: true } }),
      entry('x6', { tags, width: 500, height: 600 }),
      entry('x7', { tags, sharpness: 0.1 }),
      entry('x8', { tags: { ...tags, peoplePresent: undefined } }),
      // Status excluded by the office although the rules alone would allow it.
      entry('x9', { tags, status: 'excluded', excludedReasons: ['excluded_by_office'] }),
    ];
    const out = selectOfficeLibraryPhotos(library(photos), { ...BRIEF, copy: ['School field visit'] });
    expect(out.picks).toEqual([]);
    expect(out.eligible).toBe(0);
    expect(out.excluded).toMatchObject({ excluded_by_office: 2, not_reviewed: 1, no_consent: 1, consent_not_recorded: 1, generated: 1, too_small: 1, too_soft: 1, people_unknown: 1 });
  });

  it('returns nothing when no usable photo has anything in common with the brief: the design stays typographic', () => {
    const out = selectOfficeLibraryPhotos(library([forum, building]), { ...BRIEF, copy: ['Eid Mubarak'] });
    expect(out.picks).toEqual([]);
    expect(out.eligible).toBe(2);
  });

  it('keeps companions only within 85% of the best and at most three', () => {
    const many = Array.from({ length: 6 }, (_, i) => entry(`m${i}`, { tags: { subjects: ['workshop', 'training'], events: ['workshop'] } }));
    const out = selectOfficeLibraryPhotos(library(many), { ...BRIEF, copy: ['Quality assurance workshop'] });
    expect(out.picks).toHaveLength(3);
    expect(out.picks.map((p) => p.id)).toEqual([...many.map((m) => m.id)].sort().slice(0, 3));
    const one = selectOfficeLibraryPhotos(library(many), { ...BRIEF, copy: ['Quality assurance workshop'], max: 1 });
    expect(one.picks).toHaveLength(1);
  });

  it('reads the brief\'s English subject tags for a Sorani-only copy', () => {
    const out = selectOfficeLibraryPhotos(library([visit, forum]), { ...BRIEF, copy: ['سەردان'], eventWords: ['field_visit', 'k12'], language: 'ckb' });
    expect(out.picks[0].id).toBe(visit.id);
  });
});

describe('ingestion (ADR-280): local, idempotent by sha256, tags merged', () => {
  const source = tmp('olp-src-');
  const root = tmp('olp-lib-');
  const photoA = syntheticPhoto(1080, 1350, 11);
  const photoB = syntheticPhoto(1440, 960, 12, [90, 120, 160]);
  const tiny = syntheticPhoto(400, 300, 13);
  mkdirSync(path.join(source, 'events'), { recursive: true });
  writeFileSync(path.join(source, 'events', 'visit.png'), photoA);
  writeFileSync(path.join(source, 'forum.png'), photoB);
  writeFileSync(path.join(source, 'tiny.png'), tiny);
  writeFileSync(path.join(source, 'notes.txt'), 'not a photo');
  writeFileSync(path.join(source, 'anim.gif'), Buffer.from('GIF89a\x01\x00\x01\x00\x00\x00\x00;', 'latin1'));
  writeFileSync(path.join(source, 'phone.heic'), Buffer.concat([Buffer.from([0, 0, 0, 24]), Buffer.from('ftypheic'), Buffer.alloc(16)]));
  const fixed = () => new Date('2026-10-03T10:00:00.000Z');

  it('writes a strict manifest of the readable photos, copies them, and skips what is not a JPEG, PNG or WebP', async () => {
    const report = await ingestOfficePhotoFolder({ sourceDir: source, libraryRoot: root, clientId: 'kaae', now: fixed });
    expect(report.wrote).toBe(true);
    expect(report.added).toHaveLength(3);
    expect(report.skipped.map((s) => `${s.source}: ${s.reason}`).sort()).toEqual([
      'anim.gif: type image/gif is not allowed (JPEG, PNG or WebP only)',
      'notes.txt: not an image',
      'phone.heic: HEIC/HEIF is not supported; export it as JPEG first',
    ]);
    const read = await readOfficePhotoLibrary(officePhotoClientDir(root, 'kaae'));
    const photos = read!.library.photos;
    const visit = photos.find((p) => p.sourceName === 'events/visit.png')!;
    expect(visit.sha256).toBe(sha(photoA));
    expect(visit).toMatchObject({ width: 1080, height: 1350, orientation: 'portrait', status: 'excluded', excludedReasons: ['not_reviewed', 'people_unknown'] });
    expect(visit.features.quietArea).toBe('top');
    expect(visit.features.sharpness).toBeGreaterThan(0.45);
    expect(visit.features.dominantColors.length).toBeGreaterThan(0);
    expect(photos.find((p) => p.sourceName === 'tiny.png')!.excludedReasons).toContain('too_small');
    expect(existsSync(path.join(root, 'kaae', visit.file))).toBe(true);
    expect(readFileSync(path.join(root, 'kaae', 'tags-template.csv'), 'utf8').split('\n')[0]).toBe('id,sha256,source,description,subjects,events,keywords,shot,people,consent,usable,generated,date,note');
  });

  it('a second run over the same folder writes nothing', async () => {
    const before = readFileSync(path.join(root, 'kaae', 'library.json'));
    const again = await ingestOfficePhotoFolder({ sourceDir: source, libraryRoot: root, clientId: 'kaae', now: () => new Date('2027-01-01T00:00:00.000Z') });
    expect(again.wrote).toBe(false);
    expect(again.added).toEqual([]);
    expect(again.unchanged).toHaveLength(3);
    expect(readFileSync(path.join(root, 'kaae', 'library.json')).equals(before)).toBe(true);
  });

  it('merges a filled-in tag sheet by source name or hash, keeps those tags on re-ingestion, and the photo becomes usable', async () => {
    const csv = [
      'source,sha256,description,subjects,events,keywords,shot,people,consent,usable,date',
      `events/visit.png,,"Evaluators in a school classroom, Erbil",school; classroom,field visit,students|evaluators,classroom_or_interior,yes,granted,yes,2026-05`,
      `,${sha(photoB)},Forum hall before the opening,forum,conference,,event_or_stage,no,,yes,`,
    ].join('\n');
    const rows = parseOfficePhotoTagSheet(csv, 'csv');
    const report = await ingestOfficePhotoFolder({ sourceDir: source, libraryRoot: root, clientId: 'kaae', tagRows: rows, now: fixed });
    expect(report).toMatchObject({ wrote: true, tagRowsApplied: 2, tagRowsUnmatched: [], usable: 2, excluded: 1 });
    const again = await ingestOfficePhotoFolder({ sourceDir: source, libraryRoot: root, clientId: 'kaae', now: fixed });
    expect(again.wrote).toBe(false);
    const lib = (await readOfficePhotoLibrary(officePhotoClientDir(root, 'kaae')))!.library;
    const visit = lib.photos.find((p) => p.sourceName === 'events/visit.png')!;
    expect(visit.tags).toMatchObject({ description: 'Evaluators in a school classroom, Erbil', subjects: ['school', 'classroom'], keywords: ['students', 'evaluators'], peoplePresent: true, consent: 'granted', usable: true, date: '2026-05' });
    expect(visit.status).toBe('usable');
    const picked = selectOfficeLibraryPhotos(lib, { ...BRIEF, copy: ['KAAE K-12 Pilot Study', 'Field Visit Report'] });
    expect(picked.picks[0].id).toBe(visit.id);
    // The template now carries the tags back for the next edit.
    const template = parseOfficePhotoTagSheet(readFileSync(path.join(root, 'kaae', 'tags-template.csv'), 'utf8'), 'csv');
    expect(template.find((r) => r.id === visit.id)!.tags).toMatchObject({ usable: true, consent: 'granted', subjects: ['school', 'classroom'] });
  });

  it('refuses a malformed tag sheet with the line and column', () => {
    expect(() => parseOfficePhotoTagSheet('source,usable\na.png,perhaps', 'csv')).toThrow(/line 2 column usable/);
    expect(() => parseOfficePhotoTagSheet('source,consent\na.png,maybe', 'csv')).toThrow(/consent/);
    expect(() => parseOfficePhotoTagSheet('source,colour\na.png,red', 'csv')).toThrow(/unknown columns colour/);
    expect(() => parseOfficePhotoTagSheet('[{"source":"a.png","usable":"yes"}]', 'json')).toThrow(/usable/);
    expect(parseOfficePhotoTagSheet('[{"source":"a.png","usable":true,"peoplePresent":false}]', 'json')).toEqual([{ source: 'a.png', tags: { usable: true, peoplePresent: false } }]);
  });

  it('loads a stored photo only when it hashes to its record and stays inside its folder', async () => {
    const dir = officePhotoClientDir(root, 'kaae');
    const lib = (await readOfficePhotoLibrary(dir))!.library;
    const visit = lib.photos.find((p) => p.sourceName === 'events/visit.png')!;
    expect((await loadOfficeLibraryPhoto(dir, visit)).bytes.equals(photoA)).toBe(true);
    await expect(loadOfficeLibraryPhoto(dir, { ...visit, storedSha256: sha('other') })).rejects.toThrow(/does not match its recorded sha256/);
    await expect(loadOfficeLibraryPhoto(dir, { ...visit, file: '../../escape.png' })).rejects.toThrow(/outside its library/);
    expect(() => officePhotoClientDir(root, '../other')).toThrow(/CLIENT_INVALID/);
  });

  it('measures the same bytes to the same features, and takes its folder from HAWA_OFFICE_PHOTO_LIBRARY_DIR', async () => {
    const a = await computeOfficePhotoFeatures(photoB);
    const b = await computeOfficePhotoFeatures(Buffer.from(photoB));
    expect(b).toEqual(a);
    const flat = await computeOfficePhotoFeatures(flatPng(800, 1000, [10, 22, 40]));
    expect(flat.features.dominantColors[0]).toEqual({ hex: '#0A1628', share: 1 });
    expect(officePhotoLibraryRoot({ HAWA_OFFICE_PHOTO_LIBRARY_DIR: '/srv/hawa/photos' }, '/repo')).toBe('/srv/hawa/photos');
    expect(officePhotoLibraryRoot({}, '/repo')).toBe('/repo/data/office-photo-library');
  });
});
